import type { NavItem } from "@/types/app";

export const navigationItems: NavItem[] = [
  {
    href: "/dashboard",
    icon: "dashboard",
    label: "Tổng quan",
    roles: ["ADMIN", "LECTURER", "STUDENT"],
    section: "common",
  },
  {
    href: "/profile",
    icon: "profile",
    label: "Hồ sơ cá nhân",
    roles: ["ADMIN", "LECTURER", "STUDENT"],
    section: "common",
  },
  {
    href: "/admin/students",
    icon: "students",
    label: "Sinh viên",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/lecturers",
    icon: "lecturers",
    label: "Giảng viên",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/departments",
    icon: "departments",
    label: "Khoa",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/majors",
    icon: "majors",
    label: "Ngành",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/classes",
    icon: "classes",
    label: "Lớp sinh hoạt",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/semesters",
    icon: "semesters",
    label: "Học kỳ",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/courses",
    icon: "courses",
    label: "Môn học",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/offerings",
    icon: "offerings",
    label: "Học phần mở",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/rooms",
    icon: "rooms",
    label: "Phòng học",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/schedules",
    icon: "schedules",
    label: "Lịch học",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/grades",
    icon: "grades",
    label: "Duyệt điểm",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/regrade-requests",
    icon: "regrade",
    label: "Phúc khảo",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/reports",
    icon: "reports",
    label: "Báo cáo",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/admin/audit-logs",
    icon: "audit",
    label: "Nhật ký hệ thống",
    roles: ["ADMIN"],
    section: "admin",
  },
  {
    href: "/lecturer/courses",
    icon: "offerings",
    label: "Lớp giảng dạy",
    roles: ["LECTURER"],
    section: "teaching",
  },
  {
    href: "/lecturer/schedule",
    icon: "schedules",
    label: "Lịch giảng dạy",
    roles: ["LECTURER"],
    section: "teaching",
  },
  {
    href: "/lecturer/regrade-requests",
    icon: "regrade",
    label: "Phúc khảo",
    roles: ["LECTURER"],
    section: "teaching",
  },
  {
    href: "/student/enrollment",
    icon: "offerings",
    label: "Đăng ký học phần",
    roles: ["STUDENT"],
    section: "study",
  },
  {
    href: "/student/schedule",
    icon: "schedules",
    label: "Thời khóa biểu",
    roles: ["STUDENT"],
    section: "study",
  },
  {
    href: "/student/grades",
    icon: "grades",
    label: "Kết quả học tập",
    roles: ["STUDENT"],
    section: "study",
  },
  {
    href: "/student/regrade-requests",
    icon: "regrade",
    label: "Yêu cầu phúc khảo",
    roles: ["STUDENT"],
    section: "study",
  },
];
