import { randomUUID } from "node:crypto";
import type { SupabaseClient } from "@supabase/supabase-js";

import type { Database } from "../src/types/database";
import {
  createDemoUser,
  createServiceRoleClient,
  DEMO_BATCH,
  DEMO_PASSWORD,
  resetDemoData,
} from "./demo-utils";

const QUICK_ACCESS_DEMO_ACCOUNTS = [
  { email: "admin.demo@sms.local", label: "Admin" },
  { email: "ha.nguyen@sms.local", label: "Lecturer" },
  { email: "se22001@sms.local", label: "Student" },
] as const;

function toIso(value: string) {
  return new Date(value).toISOString();
}

async function insertRows<TableName extends keyof Database["public"]["Tables"]>(
  client: SupabaseClient<Database>,
  table: TableName,
  rows: Database["public"]["Tables"][TableName]["Insert"][],
  label: string,
) {
  if (!rows.length) {
    return;
  }

  const { error } = await client.from(table).insert(rows as never);

  if (error) {
    throw new Error(`${label}: ${error.message}`);
  }
}

function logQuickAccessDemoAccounts() {
  console.info("Demo accounts:");
  for (const account of QUICK_ACCESS_DEMO_ACCOUNTS) {
    console.info(`- ${account.label}: ${account.email} / ${DEMO_PASSWORD}`);
  }
}

export async function seedDemoData() {
  const client = createServiceRoleClient();
  await resetDemoData(client);

  const departmentIds = {
    business: randomUUID(),
    cs: randomUUID(),
    finance: randomUUID(),
  };
  const majorIds = {
    businessAdmin: randomUUID(),
    dataScience: randomUUID(),
    finance: randomUUID(),
    software: randomUUID(),
  };
  const classIds = {
    ba24a: randomUUID(),
    ds23a: randomUUID(),
    fin23a: randomUUID(),
    se22a: randomUUID(),
    se22b: randomUUID(),
  };
  const semesterIds = {
    hk1: randomUUID(),
    hk2: randomUUID(),
  };
  const roomIds = {
    a101: randomUUID(),
    a102: randomUUID(),
    b201: randomUUID(),
    b202: randomUUID(),
    c301: randomUUID(),
  };
  const courseIds = {
    bus101: randomUUID(),
    cs101: randomUUID(),
    cs102: randomUUID(),
    cs202: randomUUID(),
    ds201: randomUUID(),
    fin201: randomUUID(),
    ma101: randomUUID(),
  };
  const offeringIds = {
    bus101Current: randomUUID(),
    bus101History: randomUUID(),
    cs101History: randomUUID(),
    cs102Current: randomUUID(),
    cs202Current: randomUUID(),
    ds201Current: randomUUID(),
    fin201Current: randomUUID(),
    fin201History: randomUUID(),
    ma101History: randomUUID(),
  };
  const enrollmentIds = {
    ba24001Bus101Current: randomUUID(),
    ba24001Bus101History: randomUUID(),
    ds23001Ds201Current: randomUUID(),
    ds23001Ma101History: randomUUID(),
    ds23002Ma101History: randomUUID(),
    fin23001Fin201Current: randomUUID(),
    fin23001Fin201History: randomUUID(),
    se22001Cs101History: randomUUID(),
    se22001Cs102Current: randomUUID(),
    se22001Ma101History: randomUUID(),
    se22002Cs101History: randomUUID(),
    se22002Cs102Current: randomUUID(),
    se22002Ma101History: randomUUID(),
    se22003Cs101History: randomUUID(),
    se22003Cs202Current: randomUUID(),
    se22003Ma101History: randomUUID(),
    se22004Cs101History: randomUUID(),
    se22004Ma101History: randomUUID(),
  };
  const gradeIds = {
    ba24001Bus101History: randomUUID(),
    ds23001Ds201Current: randomUUID(),
    ds23001Ma101History: randomUUID(),
    ds23002Ma101History: randomUUID(),
    fin23001Fin201Current: randomUUID(),
    fin23001Fin201History: randomUUID(),
    se22001Cs101History: randomUUID(),
    se22001Cs102Current: randomUUID(),
    se22001Ma101History: randomUUID(),
    se22002Cs101History: randomUUID(),
    se22002Cs102Current: randomUUID(),
    se22002Ma101History: randomUUID(),
    se22003Cs101History: randomUUID(),
    se22003Ma101History: randomUUID(),
    se22004Cs101History: randomUUID(),
    se22004Ma101History: randomUUID(),
  };

  const adminId = await createDemoUser(client, {
    email: "admin.demo@sms.local",
    fullName: "Tran Hong Quan",
    metadata: { display_code: "ADM001" },
    role: "ADMIN",
  });

  const lecturerIds = {
    business: await createDemoUser(client, {
      email: "huy.vo@sms.local",
      fullName: "Vo Quoc Huy",
      metadata: { display_code: "LEC003" },
      role: "LECTURER",
    }),
    cs: await createDemoUser(client, {
      email: "ha.nguyen@sms.local",
      fullName: "Nguyen Minh Ha",
      metadata: { display_code: "LEC001" },
      role: "LECTURER",
    }),
    finance: await createDemoUser(client, {
      email: "linh.pham@sms.local",
      fullName: "Pham Thuy Linh",
      metadata: { display_code: "LEC002" },
      role: "LECTURER",
    }),
  };

  const studentIds = {
    ba24001: await createDemoUser(client, {
      email: "ba24001@sms.local",
      fullName: "Hoang Minh Khang",
      metadata: { display_code: "BA24001" },
      role: "STUDENT",
    }),
    ds23001: await createDemoUser(client, {
      email: "ds23001@sms.local",
      fullName: "Vu Thu Ha",
      metadata: { display_code: "DS23001" },
      role: "STUDENT",
    }),
    ds23002: await createDemoUser(client, {
      email: "ds23002@sms.local",
      fullName: "Bui Duc Long",
      metadata: { display_code: "DS23002" },
      role: "STUDENT",
    }),
    fin23001: await createDemoUser(client, {
      email: "fin23001@sms.local",
      fullName: "Dang Gia Han",
      metadata: { display_code: "FIN23001" },
      role: "STUDENT",
    }),
    se22001: await createDemoUser(client, {
      email: "se22001@sms.local",
      fullName: "Nguyen Anh Tuan",
      metadata: { display_code: "SE22001" },
      role: "STUDENT",
    }),
    se22002: await createDemoUser(client, {
      email: "se22002@sms.local",
      fullName: "Tran Minh Anh",
      metadata: { display_code: "SE22002" },
      role: "STUDENT",
    }),
    se22003: await createDemoUser(client, {
      email: "se22003@sms.local",
      fullName: "Le Khanh Vy",
      metadata: { display_code: "SE22003" },
      role: "STUDENT",
    }),
    se22004: await createDemoUser(client, {
      email: "se22004@sms.local",
      fullName: "Pham Gia Bao",
      metadata: { display_code: "SE22004" },
      role: "STUDENT",
    }),
  };

  await insertRows(
    client,
    "departments",
    [
      {
        code: "CNTT",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        description: "Khoa cong nghe thong tin",
        id: departmentIds.cs,
        is_active: true,
        is_demo: true,
        name: "Cong nghe thong tin",
      },
      {
        code: "KTTC",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        description: "Khoa tai chinh",
        id: departmentIds.finance,
        is_active: true,
        is_demo: true,
        name: "Tai chinh",
      },
      {
        code: "QTKD",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        description: "Khoa quan tri kinh doanh",
        id: departmentIds.business,
        is_active: true,
        is_demo: true,
        name: "Quan tri kinh doanh",
      },
    ],
    "Seed departments",
  );

  await insertRows(
    client,
    "majors",
    [
      {
        code: "SE",
        created_by: adminId,
        degree_level: "BACHELOR",
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        id: majorIds.software,
        is_active: true,
        is_demo: true,
        name: "Ky thuat phan mem",
      },
      {
        code: "DS",
        created_by: adminId,
        degree_level: "BACHELOR",
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        id: majorIds.dataScience,
        is_active: true,
        is_demo: true,
        name: "Khoa hoc du lieu",
      },
      {
        code: "FIN",
        created_by: adminId,
        degree_level: "BACHELOR",
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.finance,
        id: majorIds.finance,
        is_active: true,
        is_demo: true,
        name: "Tai chinh doanh nghiep",
      },
      {
        code: "BA",
        created_by: adminId,
        degree_level: "BACHELOR",
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.business,
        id: majorIds.businessAdmin,
        is_active: true,
        is_demo: true,
        name: "Quan tri kinh doanh",
      },
    ],
    "Seed majors",
  );

  await insertRows(
    client,
    "academic_classes",
    [
      {
        code: "SE22A",
        cohort_year: 2022,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: classIds.se22a,
        is_active: true,
        is_demo: true,
        major_id: majorIds.software,
        name: "Ky thuat phan mem 22A",
      },
      {
        code: "SE22B",
        cohort_year: 2022,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: classIds.se22b,
        is_active: true,
        is_demo: true,
        major_id: majorIds.software,
        name: "Ky thuat phan mem 22B",
      },
      {
        code: "DS23A",
        cohort_year: 2023,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: classIds.ds23a,
        is_active: true,
        is_demo: true,
        major_id: majorIds.dataScience,
        name: "Khoa hoc du lieu 23A",
      },
      {
        code: "FIN23A",
        cohort_year: 2023,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: classIds.fin23a,
        is_active: true,
        is_demo: true,
        major_id: majorIds.finance,
        name: "Tai chinh doanh nghiep 23A",
      },
      {
        code: "BA24A",
        cohort_year: 2024,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: classIds.ba24a,
        is_active: true,
        is_demo: true,
        major_id: majorIds.businessAdmin,
        name: "Quan tri kinh doanh 24A",
      },
    ],
    "Seed academic classes",
  );

  await insertRows(
    client,
    "semesters",
    [
      {
        academic_year: "2025-2026",
        code: "2025-HK1",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        end_date: "2026-01-10",
        enrollment_end: toIso("2025-08-31T23:59:59+07:00"),
        enrollment_start: toIso("2025-08-10T00:00:00+07:00"),
        id: semesterIds.hk1,
        is_current: false,
        is_demo: true,
        max_credits: 21,
        name: "Hoc ky 1 nam hoc 2025-2026",
        regrade_close_at: toIso("2026-01-25T23:59:59+07:00"),
        regrade_open_at: toIso("2026-01-15T00:00:00+07:00"),
        start_date: "2025-09-01",
      },
      {
        academic_year: "2025-2026",
        code: "2025-HK2",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        end_date: "2026-06-20",
        enrollment_end: toIso("2026-04-20T23:59:59+07:00"),
        enrollment_start: toIso("2026-02-01T00:00:00+07:00"),
        id: semesterIds.hk2,
        is_current: true,
        is_demo: true,
        max_credits: 21,
        name: "Hoc ky 2 nam hoc 2025-2026",
        regrade_close_at: toIso("2026-07-05T23:59:59+07:00"),
        regrade_open_at: toIso("2026-06-25T00:00:00+07:00"),
        start_date: "2026-02-16",
      },
    ],
    "Seed semesters",
  );

  await insertRows(
    client,
    "courses",
    [
      {
        code: "CS101",
        created_by: adminId,
        credit_hours: 3,
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        description: "Nhap mon lap trinh",
        id: courseIds.cs101,
        is_active: true,
        is_demo: true,
        name: "Nhap mon lap trinh",
        total_sessions: 30,
      },
      {
        code: "CS102",
        created_by: adminId,
        credit_hours: 3,
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        description: "Cau truc du lieu va giai thuat",
        id: courseIds.cs102,
        is_active: true,
        is_demo: true,
        name: "Cau truc du lieu",
        total_sessions: 30,
      },
      {
        code: "CS202",
        created_by: adminId,
        credit_hours: 3,
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        description: "Phat trien web voi App Router",
        id: courseIds.cs202,
        is_active: true,
        is_demo: true,
        name: "Phat trien ung dung web",
        total_sessions: 30,
      },
      {
        code: "MA101",
        created_by: adminId,
        credit_hours: 3,
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        description: "Toan cao cap nen tang",
        id: courseIds.ma101,
        is_active: true,
        is_demo: true,
        name: "Toan cao cap",
        total_sessions: 30,
      },
      {
        code: "DS201",
        created_by: adminId,
        credit_hours: 3,
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        description: "Thong ke ung dung cho khoa hoc du lieu",
        id: courseIds.ds201,
        is_active: true,
        is_demo: true,
        name: "Thong ke ung dung",
        total_sessions: 30,
      },
      {
        code: "FIN201",
        created_by: adminId,
        credit_hours: 3,
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.finance,
        description: "Tai chinh doanh nghiep can ban",
        id: courseIds.fin201,
        is_active: true,
        is_demo: true,
        name: "Tai chinh doanh nghiep",
        total_sessions: 30,
      },
      {
        code: "BUS101",
        created_by: adminId,
        credit_hours: 2,
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.business,
        description: "Nguyen ly quan tri",
        id: courseIds.bus101,
        is_active: true,
        is_demo: true,
        name: "Nguyen ly quan tri",
        total_sessions: 24,
      },
    ],
    "Seed courses",
  );

  await insertRows(
    client,
    "course_prerequisites",
    [
      {
        course_id: courseIds.cs102,
        minimum_score: 5,
        prerequisite_course_id: courseIds.cs101,
      },
      {
        course_id: courseIds.cs202,
        minimum_score: 5,
        prerequisite_course_id: courseIds.cs101,
      },
      {
        course_id: courseIds.ds201,
        minimum_score: 5,
        prerequisite_course_id: courseIds.ma101,
      },
    ],
    "Seed course prerequisites",
  );

  await insertRows(
    client,
    "rooms",
    [
      {
        building: "A",
        capacity: 60,
        code: "A101",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: roomIds.a101,
        is_active: true,
        is_demo: true,
        name: "Phong A101",
      },
      {
        building: "A",
        capacity: 60,
        code: "A102",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: roomIds.a102,
        is_active: true,
        is_demo: true,
        name: "Phong A102",
      },
      {
        building: "B",
        capacity: 45,
        code: "B201",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: roomIds.b201,
        is_active: true,
        is_demo: true,
        name: "Phong B201",
      },
      {
        building: "B",
        capacity: 45,
        code: "B202",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: roomIds.b202,
        is_active: true,
        is_demo: true,
        name: "Phong B202",
      },
      {
        building: "C",
        capacity: 40,
        code: "C301",
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        id: roomIds.c301,
        is_active: true,
        is_demo: true,
        name: "Phong C301",
      },
    ],
    "Seed rooms",
  );

  await insertRows(
    client,
    "lecturers",
    [
      {
        academic_title: "TS.",
        bio: "Giang vien phu trach nhom cong nghe thong tin",
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.cs,
        employee_code: "LEC001",
        hire_date: "2020-08-15",
        id: lecturerIds.cs,
        is_demo: true,
        office_location: "A.403",
      },
      {
        academic_title: "ThS.",
        bio: "Giang vien khoa tai chinh",
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.finance,
        employee_code: "LEC002",
        hire_date: "2021-09-10",
        id: lecturerIds.finance,
        is_demo: true,
        office_location: "B.210",
      },
      {
        academic_title: "ThS.",
        bio: "Giang vien khoa quan tri kinh doanh",
        demo_batch: DEMO_BATCH,
        department_id: departmentIds.business,
        employee_code: "LEC003",
        hire_date: "2022-02-01",
        id: lecturerIds.business,
        is_demo: true,
        office_location: "C.115",
      },
    ],
    "Seed lecturers",
  );

  await insertRows(
    client,
    "students",
    [
      {
        academic_class_id: classIds.se22a,
        address: "Quan 1, TP.HCM",
        current_status: "ACTIVE",
        date_of_birth: "2004-02-15",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000001",
        enrollment_year: 2022,
        gender: "MALE",
        id: studentIds.se22001,
        is_demo: true,
        student_code: "SE22001",
      },
      {
        academic_class_id: classIds.se22a,
        address: "Quan 3, TP.HCM",
        current_status: "ACTIVE",
        date_of_birth: "2004-07-21",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000002",
        enrollment_year: 2022,
        gender: "FEMALE",
        id: studentIds.se22002,
        is_demo: true,
        student_code: "SE22002",
      },
      {
        academic_class_id: classIds.se22b,
        address: "Thu Duc, TP.HCM",
        current_status: "ACTIVE",
        date_of_birth: "2004-11-08",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000003",
        enrollment_year: 2022,
        gender: "FEMALE",
        id: studentIds.se22003,
        is_demo: true,
        student_code: "SE22003",
      },
      {
        academic_class_id: classIds.se22b,
        address: "Bien Hoa, Dong Nai",
        current_status: "ACTIVE",
        date_of_birth: "2004-03-19",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000004",
        enrollment_year: 2022,
        gender: "MALE",
        id: studentIds.se22004,
        is_demo: true,
        student_code: "SE22004",
      },
      {
        academic_class_id: classIds.ds23a,
        address: "Binh Thanh, TP.HCM",
        current_status: "ACTIVE",
        date_of_birth: "2005-01-12",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000005",
        enrollment_year: 2023,
        gender: "FEMALE",
        id: studentIds.ds23001,
        is_demo: true,
        student_code: "DS23001",
      },
      {
        academic_class_id: classIds.ds23a,
        address: "Thu Duc, TP.HCM",
        current_status: "ACTIVE",
        date_of_birth: "2005-06-06",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000006",
        enrollment_year: 2023,
        gender: "MALE",
        id: studentIds.ds23002,
        is_demo: true,
        student_code: "DS23002",
      },
      {
        academic_class_id: classIds.fin23a,
        address: "Go Vap, TP.HCM",
        current_status: "ACTIVE",
        date_of_birth: "2005-04-27",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000007",
        enrollment_year: 2023,
        gender: "FEMALE",
        id: studentIds.fin23001,
        is_demo: true,
        student_code: "FIN23001",
      },
      {
        academic_class_id: classIds.ba24a,
        address: "Tan Binh, TP.HCM",
        current_status: "ACTIVE",
        date_of_birth: "2006-09-30",
        demo_batch: DEMO_BATCH,
        emergency_contact: "0901000008",
        enrollment_year: 2024,
        gender: "MALE",
        id: studentIds.ba24001,
        is_demo: true,
        student_code: "BA24001",
      },
    ],
    "Seed students",
  );

  await insertRows(
    client,
    "course_offerings",
    [
      {
        attendance_weight: 10,
        course_id: courseIds.cs101,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 4,
        final_weight: 60,
        id: offeringIds.cs101History,
        is_demo: true,
        max_capacity: 50,
        midterm_weight: 30,
        notes: "Hoc phan da ket thuc",
        passing_score: 5,
        registration_close_at: toIso("2025-08-31T23:59:59+07:00"),
        registration_open_at: toIso("2025-08-10T00:00:00+07:00"),
        section_code: "01",
        semester_id: semesterIds.hk1,
        status: "FINISHED",
        title: "Nhap mon lap trinh - nhom 01",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.ma101,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 6,
        final_weight: 60,
        id: offeringIds.ma101History,
        is_demo: true,
        max_capacity: 60,
        midterm_weight: 30,
        notes: "Hoc phan co diem phe duyet hoan chinh",
        passing_score: 5,
        registration_close_at: toIso("2025-08-31T23:59:59+07:00"),
        registration_open_at: toIso("2025-08-10T00:00:00+07:00"),
        section_code: "01",
        semester_id: semesterIds.hk1,
        status: "FINISHED",
        title: "Toan cao cap - nhom 01",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.fin201,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 1,
        final_weight: 60,
        id: offeringIds.fin201History,
        is_demo: true,
        max_capacity: 40,
        midterm_weight: 30,
        notes: "Hoc phan tai chinh hoc ky 1",
        passing_score: 5,
        registration_close_at: toIso("2025-08-31T23:59:59+07:00"),
        registration_open_at: toIso("2025-08-10T00:00:00+07:00"),
        section_code: "01",
        semester_id: semesterIds.hk1,
        status: "FINISHED",
        title: "Tai chinh doanh nghiep - nhom 01",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.bus101,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 1,
        final_weight: 60,
        id: offeringIds.bus101History,
        is_demo: true,
        max_capacity: 40,
        midterm_weight: 30,
        notes: "Hoc phan mo cho sinh vien khoa QTKD",
        passing_score: 5,
        registration_close_at: toIso("2025-08-31T23:59:59+07:00"),
        registration_open_at: toIso("2025-08-10T00:00:00+07:00"),
        section_code: "01",
        semester_id: semesterIds.hk1,
        status: "FINISHED",
        title: "Nguyen ly quan tri - nhom 01",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.cs102,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 2,
        final_weight: 60,
        id: offeringIds.cs102Current,
        is_demo: true,
        max_capacity: 45,
        midterm_weight: 30,
        notes: "Hoc phan dang mo de test dang ky va duyet diem",
        passing_score: 5,
        registration_close_at: toIso("2026-04-20T23:59:59+07:00"),
        registration_open_at: toIso("2026-02-10T00:00:00+07:00"),
        section_code: "01",
        semester_id: semesterIds.hk2,
        status: "OPEN",
        title: "Cau truc du lieu - nhom 01",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.cs202,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 1,
        final_weight: 60,
        id: offeringIds.cs202Current,
        is_demo: true,
        max_capacity: 40,
        midterm_weight: 30,
        notes: "Hoc phan web app demo",
        passing_score: 5,
        registration_close_at: toIso("2026-04-20T23:59:59+07:00"),
        registration_open_at: toIso("2026-02-10T00:00:00+07:00"),
        section_code: "01",
        semester_id: semesterIds.hk2,
        status: "OPEN",
        title: "Phat trien ung dung web - nhom 01",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.ds201,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 1,
        final_weight: 60,
        id: offeringIds.ds201Current,
        is_demo: true,
        max_capacity: 35,
        midterm_weight: 30,
        notes: "Hoc phan co diem nhap nhap de test luong giang vien",
        passing_score: 5,
        registration_close_at: toIso("2026-04-20T23:59:59+07:00"),
        registration_open_at: toIso("2026-02-10T00:00:00+07:00"),
        section_code: "01",
        semester_id: semesterIds.hk2,
        status: "OPEN",
        title: "Thong ke ung dung - nhom 01",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.fin201,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 1,
        final_weight: 60,
        id: offeringIds.fin201Current,
        is_demo: true,
        max_capacity: 35,
        midterm_weight: 30,
        notes: "Hoc phan tai chinh dang co diem da duyet",
        passing_score: 5,
        registration_close_at: toIso("2026-04-20T23:59:59+07:00"),
        registration_open_at: toIso("2026-02-10T00:00:00+07:00"),
        section_code: "02",
        semester_id: semesterIds.hk2,
        status: "OPEN",
        title: "Tai chinh doanh nghiep - nhom 02",
      },
      {
        attendance_weight: 10,
        course_id: courseIds.bus101,
        created_by: adminId,
        demo_batch: DEMO_BATCH,
        enrolled_count: 1,
        final_weight: 60,
        id: offeringIds.bus101Current,
        is_demo: true,
        max_capacity: 35,
        midterm_weight: 30,
        notes: "Hoc phan mo cho BA24A",
        passing_score: 5,
        registration_close_at: toIso("2026-04-20T23:59:59+07:00"),
        registration_open_at: toIso("2026-02-10T00:00:00+07:00"),
        section_code: "02",
        semester_id: semesterIds.hk2,
        status: "OPEN",
        title: "Nguyen ly quan tri - nhom 02",
      },
    ],
    "Seed course offerings",
  );

  await insertRows(
    client,
    "teaching_assignments",
    [
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.cs101History,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.cs,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.ma101History,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.cs,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.fin201History,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.finance,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.bus101History,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.business,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.cs102Current,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.cs,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.cs202Current,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.cs,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.ds201Current,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.cs,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.fin201Current,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.finance,
      },
      {
        assignment_role: "PRIMARY",
        course_offering_id: offeringIds.bus101Current,
        demo_batch: DEMO_BATCH,
        id: randomUUID(),
        is_demo: true,
        is_primary: true,
        lecturer_id: lecturerIds.business,
      },
    ],
    "Seed teaching assignments",
  );

  await insertRows(
    client,
    "schedules",
    [
      {
        course_offering_id: offeringIds.cs101History,
        day_of_week: 1,
        demo_batch: DEMO_BATCH,
        end_date: "2026-01-10",
        end_time: "09:30",
        id: randomUUID(),
        is_demo: true,
        note: "Ly thuyet phong A101",
        room_id: roomIds.a101,
        start_date: "2025-09-01",
        start_time: "07:30",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.ma101History,
        day_of_week: 3,
        demo_batch: DEMO_BATCH,
        end_date: "2026-01-10",
        end_time: "09:30",
        id: randomUUID(),
        is_demo: true,
        note: "Ca sang phong A102",
        room_id: roomIds.a102,
        start_date: "2025-09-01",
        start_time: "07:30",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.fin201History,
        day_of_week: 4,
        demo_batch: DEMO_BATCH,
        end_date: "2026-01-10",
        end_time: "11:30",
        id: randomUUID(),
        is_demo: true,
        note: "Phong B202",
        room_id: roomIds.b202,
        start_date: "2025-09-01",
        start_time: "09:30",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.bus101History,
        day_of_week: 2,
        demo_batch: DEMO_BATCH,
        end_date: "2026-01-10",
        end_time: "15:00",
        id: randomUUID(),
        is_demo: true,
        note: "Phong B201",
        room_id: roomIds.b201,
        start_date: "2025-09-01",
        start_time: "13:00",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.cs102Current,
        day_of_week: 1,
        demo_batch: DEMO_BATCH,
        end_date: "2026-06-20",
        end_time: "11:45",
        id: randomUUID(),
        is_demo: true,
        note: "Ca sang phong A101",
        room_id: roomIds.a101,
        start_date: "2026-02-16",
        start_time: "09:45",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.cs202Current,
        day_of_week: 2,
        demo_batch: DEMO_BATCH,
        end_date: "2026-06-20",
        end_time: "09:30",
        id: randomUUID(),
        is_demo: true,
        note: "Phong C301",
        room_id: roomIds.c301,
        start_date: "2026-02-16",
        start_time: "07:30",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.ds201Current,
        day_of_week: 3,
        demo_batch: DEMO_BATCH,
        end_date: "2026-06-20",
        end_time: "11:45",
        id: randomUUID(),
        is_demo: true,
        note: "Phong A102",
        room_id: roomIds.a102,
        start_date: "2026-02-16",
        start_time: "09:45",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.fin201Current,
        day_of_week: 4,
        demo_batch: DEMO_BATCH,
        end_date: "2026-06-20",
        end_time: "15:00",
        id: randomUUID(),
        is_demo: true,
        note: "Phong B202",
        room_id: roomIds.b202,
        start_date: "2026-02-16",
        start_time: "13:00",
        week_pattern: "ALL",
      },
      {
        course_offering_id: offeringIds.bus101Current,
        day_of_week: 5,
        demo_batch: DEMO_BATCH,
        end_date: "2026-06-20",
        end_time: "11:30",
        id: randomUUID(),
        is_demo: true,
        note: "Phong B201",
        room_id: roomIds.b201,
        start_date: "2026-02-16",
        start_time: "09:30",
        week_pattern: "ALL",
      },
    ],
    "Seed schedules",
  );

  await insertRows(
    client,
    "enrollments",
    [
      {
        approved_by: adminId,
        course_offering_id: offeringIds.cs101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-20T08:00:00+07:00"),
        id: enrollmentIds.se22001Cs101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22001,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.cs101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-20T08:05:00+07:00"),
        id: enrollmentIds.se22002Cs101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22002,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.cs101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-20T08:10:00+07:00"),
        id: enrollmentIds.se22003Cs101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22003,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.cs101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-20T08:15:00+07:00"),
        id: enrollmentIds.se22004Cs101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22004,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.ma101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-21T08:00:00+07:00"),
        id: enrollmentIds.se22001Ma101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22001,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.ma101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-21T08:05:00+07:00"),
        id: enrollmentIds.se22002Ma101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22002,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.ma101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-21T08:10:00+07:00"),
        id: enrollmentIds.se22003Ma101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22003,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.ma101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-21T08:15:00+07:00"),
        id: enrollmentIds.se22004Ma101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.se22004,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.ma101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-21T08:20:00+07:00"),
        id: enrollmentIds.ds23001Ma101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.ds23001,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.ma101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-21T08:25:00+07:00"),
        id: enrollmentIds.ds23002Ma101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.ds23002,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.fin201History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-22T08:00:00+07:00"),
        id: enrollmentIds.fin23001Fin201History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.fin23001,
      },
      {
        approved_by: adminId,
        course_offering_id: offeringIds.bus101History,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2025-08-22T08:05:00+07:00"),
        id: enrollmentIds.ba24001Bus101History,
        is_demo: true,
        status: "COMPLETED",
        student_id: studentIds.ba24001,
      },
      {
        course_offering_id: offeringIds.cs102Current,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2026-02-12T09:00:00+07:00"),
        id: enrollmentIds.se22001Cs102Current,
        is_demo: true,
        status: "ENROLLED",
        student_id: studentIds.se22001,
      },
      {
        course_offering_id: offeringIds.cs102Current,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2026-02-12T09:05:00+07:00"),
        id: enrollmentIds.se22002Cs102Current,
        is_demo: true,
        status: "ENROLLED",
        student_id: studentIds.se22002,
      },
      {
        course_offering_id: offeringIds.cs202Current,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2026-02-12T09:10:00+07:00"),
        id: enrollmentIds.se22003Cs202Current,
        is_demo: true,
        status: "ENROLLED",
        student_id: studentIds.se22003,
      },
      {
        course_offering_id: offeringIds.ds201Current,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2026-02-12T09:15:00+07:00"),
        id: enrollmentIds.ds23001Ds201Current,
        is_demo: true,
        status: "ENROLLED",
        student_id: studentIds.ds23001,
      },
      {
        course_offering_id: offeringIds.fin201Current,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2026-02-12T09:20:00+07:00"),
        id: enrollmentIds.fin23001Fin201Current,
        is_demo: true,
        status: "ENROLLED",
        student_id: studentIds.fin23001,
      },
      {
        course_offering_id: offeringIds.bus101Current,
        demo_batch: DEMO_BATCH,
        enrolled_at: toIso("2026-02-12T09:25:00+07:00"),
        id: enrollmentIds.ba24001Bus101Current,
        is_demo: true,
        status: "ENROLLED",
        student_id: studentIds.ba24001,
      },
    ],
    "Seed enrollments",
  );

  await insertRows(
    client,
    "grades",
    [
      {
        approved_at: toIso("2026-01-12T10:00:00+07:00"),
        approved_by: adminId,
        attendance_score: 8,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22001Cs101History,
        final_score: 8.5,
        id: gradeIds.se22001Cs101History,
        is_demo: true,
        midterm_score: 7.5,
        remark: "Diem lich su da khoa",
        status: "LOCKED",
        submitted_at: toIso("2026-01-11T12:00:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T10:05:00+07:00"),
        approved_by: adminId,
        attendance_score: 9,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22002Cs101History,
        final_score: 9,
        id: gradeIds.se22002Cs101History,
        is_demo: true,
        locked_at: toIso("2026-01-13T09:00:00+07:00"),
        locked_by: adminId,
        midterm_score: 8,
        remark: "Ket qua tot",
        status: "LOCKED",
        submitted_at: toIso("2026-01-11T12:05:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T10:10:00+07:00"),
        approved_by: adminId,
        attendance_score: 8,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22003Cs101History,
        final_score: 7,
        id: gradeIds.se22003Cs101History,
        is_demo: true,
        midterm_score: 7,
        remark: "Da phe duyet",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T12:10:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T10:15:00+07:00"),
        approved_by: adminId,
        attendance_score: 7,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22004Cs101History,
        final_score: 6.5,
        id: gradeIds.se22004Cs101History,
        is_demo: true,
        midterm_score: 6,
        remark: "Vua du dieu kien",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T12:15:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T11:00:00+07:00"),
        approved_by: adminId,
        attendance_score: 8,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22001Ma101History,
        final_score: 7.5,
        id: gradeIds.se22001Ma101History,
        is_demo: true,
        midterm_score: 7,
        remark: "Diem toan co ban",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T13:00:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T11:05:00+07:00"),
        approved_by: adminId,
        attendance_score: 8.5,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22002Ma101History,
        final_score: 8,
        id: gradeIds.se22002Ma101History,
        is_demo: true,
        midterm_score: 7.5,
        remark: "Da khoa de demo phuc khao",
        status: "LOCKED",
        submitted_at: toIso("2026-01-11T13:05:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T11:10:00+07:00"),
        approved_by: adminId,
        attendance_score: 7.5,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22003Ma101History,
        final_score: 7,
        id: gradeIds.se22003Ma101History,
        is_demo: true,
        midterm_score: 6.5,
        remark: "Diem trung binh kha",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T13:10:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T11:15:00+07:00"),
        approved_by: adminId,
        attendance_score: 7,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22004Ma101History,
        final_score: 6.5,
        id: gradeIds.se22004Ma101History,
        is_demo: true,
        midterm_score: 6,
        remark: "Dat yeu cau",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T13:15:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T11:20:00+07:00"),
        approved_by: adminId,
        attendance_score: 9,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.ds23001Ma101History,
        final_score: 8.5,
        id: gradeIds.ds23001Ma101History,
        is_demo: true,
        midterm_score: 8,
        remark: "Du dieu kien hoc DS201",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T13:20:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T11:25:00+07:00"),
        approved_by: adminId,
        attendance_score: 7.5,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.ds23002Ma101History,
        final_score: 6.5,
        id: gradeIds.ds23002Ma101History,
        is_demo: true,
        midterm_score: 6.5,
        remark: "Diem lich su DS",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T13:25:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        approved_at: toIso("2026-01-12T11:30:00+07:00"),
        approved_by: adminId,
        attendance_score: 8,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.fin23001Fin201History,
        final_score: 9,
        id: gradeIds.fin23001Fin201History,
        is_demo: true,
        midterm_score: 8.5,
        remark: "Da cap nhat sau phuc khao",
        status: "LOCKED",
        submitted_at: toIso("2026-01-11T13:30:00+07:00"),
        submitted_by: lecturerIds.finance,
      },
      {
        approved_at: toIso("2026-01-12T11:35:00+07:00"),
        approved_by: adminId,
        attendance_score: 8,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.ba24001Bus101History,
        final_score: 8,
        id: gradeIds.ba24001Bus101History,
        is_demo: true,
        midterm_score: 7.5,
        remark: "Hoan thanh hoc ky 1",
        status: "APPROVED",
        submitted_at: toIso("2026-01-11T13:35:00+07:00"),
        submitted_by: lecturerIds.business,
      },
      {
        attendance_score: 9,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22001Cs102Current,
        final_score: 8,
        id: gradeIds.se22001Cs102Current,
        is_demo: true,
        midterm_score: 8,
        remark: "Da gui admin duyet",
        status: "SUBMITTED",
        submitted_at: toIso("2026-04-02T15:00:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        attendance_score: 8,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22002Cs102Current,
        final_score: 7.5,
        id: gradeIds.se22002Cs102Current,
        is_demo: true,
        midterm_score: 7.5,
        remark: "Cho admin duyet",
        status: "SUBMITTED",
        submitted_at: toIso("2026-04-02T15:05:00+07:00"),
        submitted_by: lecturerIds.cs,
      },
      {
        attendance_score: 8.5,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.ds23001Ds201Current,
        final_score: 0,
        id: gradeIds.ds23001Ds201Current,
        is_demo: true,
        midterm_score: 7,
        remark: "Dang nhap diem nhap",
        status: "DRAFT",
      },
      {
        approved_at: toIso("2026-04-01T10:30:00+07:00"),
        approved_by: adminId,
        attendance_score: 9,
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.fin23001Fin201Current,
        final_score: 8.5,
        id: gradeIds.fin23001Fin201Current,
        is_demo: true,
        midterm_score: 8,
        remark: "Da duyet som cho demo",
        status: "APPROVED",
        submitted_at: toIso("2026-03-31T18:00:00+07:00"),
        submitted_by: lecturerIds.finance,
      },
    ],
    "Seed grades",
  );

  await insertRows(
    client,
    "grade_change_logs",
    [
      {
        change_type: "REGRADE_RESOLUTION",
        changed_by: adminId,
        demo_batch: DEMO_BATCH,
        grade_id: gradeIds.fin23001Fin201History,
        id: randomUUID(),
        is_demo: true,
        new_payload: {
          remark: "Da cap nhat sau phuc khao",
          total_score: 8.75,
        },
        note: "Tang diem do cong nham 1 cau tu luan",
        old_payload: {
          remark: "Ban dau",
          total_score: 8.25,
        },
      },
    ],
    "Seed grade change logs",
  );

  await insertRows(
    client,
    "regrade_requests",
    [
      {
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.se22001Cs101History,
        grade_id: gradeIds.se22001Cs101History,
        id: randomUUID(),
        is_demo: true,
        previous_total_score: 8.15,
        reason: "Sinh vien de nghi kiem tra lai phan diem giua ky.",
        status: "PENDING",
        student_id: studentIds.se22001,
      },
      {
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.ds23001Ma101History,
        grade_id: gradeIds.ds23001Ma101History,
        id: randomUUID(),
        is_demo: true,
        previous_total_score: 8.4,
        reason: "Can doi chieu diem chuyen can va bai tap thanh phan.",
        reviewed_at: toIso("2026-01-18T09:00:00+07:00"),
        reviewed_by: lecturerIds.cs,
        status: "UNDER_REVIEW",
        student_id: studentIds.ds23001,
      },
      {
        demo_batch: DEMO_BATCH,
        enrollment_id: enrollmentIds.fin23001Fin201History,
        grade_id: gradeIds.fin23001Fin201History,
        id: randomUUID(),
        is_demo: true,
        previous_total_score: 8.25,
        reason: "Sinh vien de nghi xem lai dap an tu luan cau 3.",
        resolution_note: "Da doi chieu bai thi va tang diem theo bien ban phuc khao.",
        resolved_total_score: 8.75,
        reviewed_at: toIso("2026-01-20T15:00:00+07:00"),
        reviewed_by: adminId,
        status: "RESOLVED",
        student_id: studentIds.fin23001,
      },
    ],
    "Seed regrade requests",
  );

  await insertRows(
    client,
    "audit_logs",
    [
      {
        action: "AUTH_LOGIN",
        actor_id: adminId,
        actor_role: "ADMIN",
        demo_batch: DEMO_BATCH,
        entity_type: "auth",
        is_demo: true,
        metadata: { via: "seed-script" },
        target_user_id: adminId,
      },
      {
        action: "USER_PROVISIONED",
        actor_id: adminId,
        actor_role: "ADMIN",
        demo_batch: DEMO_BATCH,
        entity_id: lecturerIds.cs,
        entity_type: "profiles",
        is_demo: true,
        metadata: { email: "ha.nguyen@sms.local", role: "LECTURER" },
        target_user_id: lecturerIds.cs,
      },
      {
        action: "USER_PROVISIONED",
        actor_id: adminId,
        actor_role: "ADMIN",
        demo_batch: DEMO_BATCH,
        entity_id: studentIds.se22001,
        entity_type: "profiles",
        is_demo: true,
        metadata: { email: "se22001@sms.local", role: "STUDENT" },
        target_user_id: studentIds.se22001,
      },
      {
        action: "ENROLLMENT_REGISTER_TRIGGERED",
        actor_id: studentIds.se22001,
        actor_role: "STUDENT",
        demo_batch: DEMO_BATCH,
        entity_id: offeringIds.cs102Current,
        entity_type: "course_offerings",
        is_demo: true,
        metadata: { section_code: "01" },
        target_user_id: studentIds.se22001,
      },
      {
        action: "GRADE_SHEET_SUBMITTED",
        actor_id: lecturerIds.cs,
        actor_role: "LECTURER",
        demo_batch: DEMO_BATCH,
        entity_id: offeringIds.cs102Current,
        entity_type: "course_offerings",
        is_demo: true,
        metadata: { enrollment_count: 2 },
      },
      {
        action: "GRADE_STATUS_CHANGED",
        actor_id: adminId,
        actor_role: "ADMIN",
        demo_batch: DEMO_BATCH,
        entity_id: gradeIds.fin23001Fin201Current,
        entity_type: "grades",
        is_demo: true,
        metadata: { next_status: "APPROVED" },
        target_user_id: studentIds.fin23001,
      },
      {
        action: "REGRADE_REQUEST_CREATED",
        actor_id: studentIds.se22001,
        actor_role: "STUDENT",
        demo_batch: DEMO_BATCH,
        entity_id: gradeIds.se22001Cs101History,
        entity_type: "regrade_requests",
        is_demo: true,
        metadata: { status: "PENDING" },
        target_user_id: studentIds.se22001,
      },
      {
        action: "REGRADE_REQUEST_RESOLVED",
        actor_id: adminId,
        actor_role: "ADMIN",
        demo_batch: DEMO_BATCH,
        entity_id: gradeIds.fin23001Fin201History,
        entity_type: "regrade_requests",
        is_demo: true,
        metadata: { status: "RESOLVED" },
        target_user_id: studentIds.fin23001,
      },
    ],
    "Seed audit logs",
  );

  console.info(`Seed demo batch "${DEMO_BATCH}" completed successfully.`);
  logQuickAccessDemoAccounts();
}
