-- Canonical baseline schema for SMS (reset-from-scratch).
-- Generated by squashing archive migrations and applying final canonical overrides.
-- This file intentionally excludes legacy compatibility layers (report_status, overload RPC aliases).

-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/0001_init_sms.sql
-- =====================================================================

create extension if not exists pgcrypto;
create extension if not exists citext;
create extension if not exists btree_gist;
create extension if not exists pg_trgm;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'profile_status') then
    create type profile_status as enum ('ACTIVE', 'INACTIVE', 'LOCKED');
  end if;
  if not exists (select 1 from pg_type where typname = 'student_status') then
    create type student_status as enum ('ACTIVE', 'SUSPENDED', 'GRADUATED', 'DROPPED');
  end if;
  if not exists (select 1 from pg_type where typname = 'offering_status') then
    create type offering_status as enum ('DRAFT', 'OPEN', 'CLOSED', 'FINISHED', 'CANCELLED');
  end if;
  if not exists (select 1 from pg_type where typname = 'enrollment_status') then
    create type enrollment_status as enum ('ENROLLED', 'DROPPED', 'COMPLETED');
  end if;
  if not exists (select 1 from pg_type where typname = 'grade_status') then
    create type grade_status as enum ('DRAFT', 'SUBMITTED', 'APPROVED', 'LOCKED');
  end if;
  if not exists (select 1 from pg_type where typname = 'regrade_status') then
    create type regrade_status as enum ('PENDING', 'UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'CANCELLED');
  end if;
end $$;

-- Base schema definitions must exist before functions, triggers, and RLS policies
-- that reference these relations.
create table if not exists public.roles (
  code text primary key,
  name text not null,
  description text
);

insert into public.roles (code, name, description)
values
  ('ADMIN', 'Administrator', 'Full access to manage the system'),
  ('LECTURER', 'Lecturer', 'Can manage grades and teaching workload'),
  ('STUDENT', 'Student', 'Can manage personal study activities')
on conflict (code) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email citext not null unique,
  full_name text not null,
  role_code text not null references public.roles (code),
  status profile_status not null default 'ACTIVE',
  phone text,
  avatar_url text,
  must_change_password boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.departments (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.majors (
  id uuid primary key default gen_random_uuid(),
  department_id uuid not null references public.departments (id) on delete restrict,
  code text not null unique,
  name text not null,
  degree_level text not null default 'UNDERGRADUATE',
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.academic_classes (
  id uuid primary key default gen_random_uuid(),
  major_id uuid not null references public.majors (id) on delete restrict,
  code text not null unique,
  name text not null,
  cohort_year integer not null check (cohort_year >= 2000),
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.semesters (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  academic_year text not null,
  start_date date not null,
  end_date date not null,
  enrollment_start timestamptz not null,
  enrollment_end timestamptz not null,
  regrade_open_at timestamptz,
  regrade_close_at timestamptz,
  max_credits integer not null default 21 check (max_credits > 0),
  is_current boolean not null default false,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint semesters_date_check check (start_date <= end_date),
  constraint semesters_enrollment_window_check check (enrollment_start < enrollment_end),
  constraint semesters_regrade_window_check check (
    regrade_open_at is null
    or regrade_close_at is null
    or regrade_open_at < regrade_close_at
  )
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  department_id uuid not null references public.departments (id) on delete restrict,
  code text not null unique,
  name text not null,
  credit_hours integer not null check (credit_hours > 0),
  total_sessions smallint not null default 15 check (total_sessions > 0),
  description text,
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.course_prerequisites (
  course_id uuid not null references public.courses (id) on delete cascade,
  prerequisite_course_id uuid not null references public.courses (id) on delete restrict,
  minimum_score numeric(4, 2) not null default 5.00 check (minimum_score >= 0 and minimum_score <= 10),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (course_id, prerequisite_course_id),
  constraint course_prerequisites_self_check check (course_id <> prerequisite_course_id)
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  building text,
  capacity integer not null check (capacity > 0),
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lecturers (
  id uuid primary key references public.profiles (id) on delete cascade,
  employee_code text not null unique,
  department_id uuid not null references public.departments (id) on delete restrict,
  academic_title text,
  hire_date date,
  office_location text,
  bio text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.students (
  id uuid primary key references public.profiles (id) on delete cascade,
  student_code text not null unique,
  academic_class_id uuid not null references public.academic_classes (id) on delete restrict,
  enrollment_year integer not null check (enrollment_year >= 2000),
  current_status student_status not null default 'ACTIVE',
  gender text,
  date_of_birth date,
  address text,
  emergency_contact text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.course_offerings (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses (id) on delete restrict,
  semester_id uuid not null references public.semesters (id) on delete restrict,
  section_code text not null,
  title text,
  max_capacity integer not null check (max_capacity > 0),
  enrolled_count integer not null default 0 check (enrolled_count >= 0),
  registration_open_at timestamptz not null,
  registration_close_at timestamptz not null,
  attendance_weight numeric(5, 2) not null default 10.00 check (attendance_weight >= 0 and attendance_weight <= 100),
  midterm_weight numeric(5, 2) not null default 30.00 check (midterm_weight >= 0 and midterm_weight <= 100),
  final_weight numeric(5, 2) not null default 60.00 check (final_weight >= 0 and final_weight <= 100),
  passing_score numeric(4, 2) not null default 5.00 check (passing_score >= 0 and passing_score <= 10),
  status offering_status not null default 'DRAFT',
  notes text,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint course_offerings_registration_window_check check (registration_open_at < registration_close_at),
  constraint course_offerings_weight_sum_check check (
    attendance_weight + midterm_weight + final_weight = 100.00
  ),
  constraint course_offerings_unique_section unique (semester_id, course_id, section_code)
);

create table if not exists public.teaching_assignments (
  id uuid primary key default gen_random_uuid(),
  course_offering_id uuid not null references public.course_offerings (id) on delete cascade,
  lecturer_id uuid not null references public.lecturers (id) on delete cascade,
  assignment_role text not null default 'PRIMARY',
  is_primary boolean not null default false,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  unique (course_offering_id, lecturer_id)
);

create table if not exists public.schedules (
  id uuid primary key default gen_random_uuid(),
  course_offering_id uuid not null references public.course_offerings (id) on delete cascade,
  room_id uuid references public.rooms (id) on delete set null,
  day_of_week smallint not null check (day_of_week between 1 and 7),
  start_time time not null,
  end_time time not null,
  week_pattern text not null default 'ALL',
  start_date date,
  end_date date,
  note text,
  time_range int4range generated always as (
    int4range(
      (extract(hour from start_time)::int * 60) + extract(minute from start_time)::int,
      (extract(hour from end_time)::int * 60) + extract(minute from end_time)::int,
      '[)'
    )
  ) stored,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint schedules_time_check check (start_time < end_time),
  constraint schedules_date_check check (start_date is null or end_date is null or start_date <= end_date)
);

create table if not exists public.enrollments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students (id) on delete cascade,
  course_offering_id uuid not null references public.course_offerings (id) on delete cascade,
  status enrollment_status not null default 'ENROLLED',
  enrolled_at timestamptz not null default timezone('utc', now()),
  dropped_at timestamptz,
  drop_reason text,
  approved_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint enrollments_unique_student_offering unique (student_id, course_offering_id)
);

create table if not exists public.grades (
  id uuid primary key default gen_random_uuid(),
  enrollment_id uuid not null unique references public.enrollments (id) on delete cascade,
  attendance_score numeric(4, 2) check (attendance_score >= 0 and attendance_score <= 10),
  midterm_score numeric(4, 2) check (midterm_score >= 0 and midterm_score <= 10),
  final_score numeric(4, 2) check (final_score >= 0 and final_score <= 10),
  total_score numeric(4, 2),
  letter_grade text,
  gpa_value numeric(3, 2),
  status grade_status not null default 'DRAFT',
  submitted_at timestamptz,
  submitted_by uuid references public.profiles (id),
  approved_at timestamptz,
  approved_by uuid references public.profiles (id),
  locked_at timestamptz,
  locked_by uuid references public.profiles (id),
  remark text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.grade_change_logs (
  id uuid primary key default gen_random_uuid(),
  grade_id uuid not null references public.grades (id) on delete cascade,
  changed_by uuid references public.profiles (id),
  change_type text not null,
  old_payload jsonb not null default '{}'::jsonb,
  new_payload jsonb not null default '{}'::jsonb,
  note text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.regrade_requests (
  id uuid primary key default gen_random_uuid(),
  grade_id uuid not null references public.grades (id) on delete cascade,
  enrollment_id uuid not null references public.enrollments (id) on delete cascade,
  student_id uuid not null references public.students (id) on delete cascade,
  reason text not null,
  status regrade_status not null default 'PENDING',
  previous_total_score numeric(4, 2),
  resolved_total_score numeric(4, 2),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles (id),
  resolution_note text,
  is_demo boolean not null default false,
  demo_batch text,
  submitted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles (id),
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  target_user_id uuid references public.profiles (id),
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  user_agent text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists teaching_assignments_one_primary_idx
  on public.teaching_assignments (course_offering_id)
  where is_primary;

create unique index if not exists regrade_requests_one_open_request_idx
  on public.regrade_requests (grade_id, student_id)
  where status in ('PENDING', 'UNDER_REVIEW');

create index if not exists profiles_role_idx on public.profiles (role_code, status);
create index if not exists departments_active_idx on public.departments (is_active);
create index if not exists majors_department_idx on public.majors (department_id);
create index if not exists academic_classes_major_idx on public.academic_classes (major_id, cohort_year);
create index if not exists lecturers_department_idx on public.lecturers (department_id);
create index if not exists students_class_idx on public.students (academic_class_id, current_status);
create index if not exists course_offerings_semester_idx on public.course_offerings (semester_id, status);
create index if not exists teaching_assignments_lecturer_idx on public.teaching_assignments (lecturer_id, course_offering_id);
create index if not exists schedules_offering_idx on public.schedules (course_offering_id, day_of_week);
create index if not exists enrollments_student_idx on public.enrollments (student_id, status);
create index if not exists enrollments_offering_idx on public.enrollments (course_offering_id, status);
create index if not exists grades_status_idx on public.grades (status);
create index if not exists regrade_requests_status_idx on public.regrade_requests (status, student_id);
create index if not exists audit_logs_action_idx on public.audit_logs (action, created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'schedules_room_overlap_excl'
  ) then
    alter table public.schedules
      add constraint schedules_room_overlap_excl
      exclude using gist (
        room_id with =,
        day_of_week with =,
        time_range with &&
      )
      where (room_id is not null);
  end if;
end $$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role_code
  from public.profiles p
  where p.id = auth.uid()
    and p.status = 'ACTIVE'
  limit 1;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() = 'ADMIN', false);
$$;

create or replace function public.is_lecturer_assigned(p_offering_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.teaching_assignments ta
    where ta.course_offering_id = p_offering_id
      and ta.lecturer_id = auth.uid()
  );
$$;

create or replace function public.score_to_letter(p_score numeric)
returns text
language plpgsql
immutable
as $$
begin
  if p_score is null then
    return null;
  elsif p_score >= 8.5 then
    return 'A';
  elsif p_score >= 8.0 then
    return 'B+';
  elsif p_score >= 7.0 then
    return 'B';
  elsif p_score >= 6.5 then
    return 'C+';
  elsif p_score >= 5.5 then
    return 'C';
  elsif p_score >= 5.0 then
    return 'D+';
  elsif p_score >= 4.0 then
    return 'D';
  else
    return 'F';
  end if;
end;
$$;

create or replace function public.score_to_gpa(p_score numeric)
returns numeric
language plpgsql
immutable
as $$
begin
  if p_score is null then
    return null;
  elsif p_score >= 8.5 then
    return 4.0;
  elsif p_score >= 8.0 then
    return 3.5;
  elsif p_score >= 7.0 then
    return 3.0;
  elsif p_score >= 6.5 then
    return 2.5;
  elsif p_score >= 5.5 then
    return 2.0;
  elsif p_score >= 5.0 then
    return 1.5;
  elsif p_score >= 4.0 then
    return 1.0;
  else
    return 0.0;
  end if;
end;
$$;

create or replace function public.recompute_grade_derived_fields()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_weights record;
  v_total numeric;
begin
  select
    co.attendance_weight,
    co.midterm_weight,
    co.final_weight
  into v_weights
  from public.enrollments e
  join public.course_offerings co on co.id = e.course_offering_id
  where e.id = new.enrollment_id;

  if new.attendance_score is not null
     and new.midterm_score is not null
     and new.final_score is not null then
    v_total := round(
      (
        (new.attendance_score * v_weights.attendance_weight) +
        (new.midterm_score * v_weights.midterm_weight) +
        (new.final_score * v_weights.final_weight)
      ) / 100.0,
      2
    );

    new.total_score := v_total;
    new.letter_grade := public.score_to_letter(v_total);
    new.gpa_value := public.score_to_gpa(v_total);
  else
    new.total_score := null;
    new.letter_grade := null;
    new.gpa_value := null;
  end if;

  return new;
end;
$$;

create or replace function public.apply_grade_status_transition()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_role text := public.current_user_role();
  v_actor_id uuid := auth.uid();
begin
  if tg_op <> 'UPDATE' then
    return new;
  end if;

  if v_actor_id is null then
    raise exception 'Authentication required';
  end if;

  if v_role is null then
    raise exception 'Active profile with role is required';
  end if;

  if old.status = 'LOCKED' and v_role <> 'ADMIN' then
    raise exception 'Locked grades can only be changed by admin';
  end if;

  if old.status <> 'DRAFT'
     and (
       new.attendance_score is distinct from old.attendance_score
       or new.midterm_score is distinct from old.midterm_score
       or new.final_score is distinct from old.final_score
     )
  then
    raise exception 'Scores can only be edited while grade status is DRAFT';
  end if;

  if new.status is not distinct from old.status then
    return new;
  end if;

  if old.status = 'DRAFT' and new.status = 'SUBMITTED' then
    if v_role not in ('LECTURER', 'ADMIN') then
      raise exception 'Only lecturer or admin can submit grades';
    end if;
    if new.attendance_score is null or new.midterm_score is null or new.final_score is null then
      raise exception 'Cannot submit grade with incomplete component scores';
    end if;
    new.submitted_at := timezone('utc', now());
    new.submitted_by := v_actor_id;
  elsif old.status = 'SUBMITTED' and new.status = 'APPROVED' then
    if v_role <> 'ADMIN' then
      raise exception 'Only admin can approve grades';
    end if;
    new.approved_at := timezone('utc', now());
    new.approved_by := v_actor_id;
  elsif old.status = 'SUBMITTED' and new.status = 'DRAFT' then
    if v_role <> 'ADMIN' then
      raise exception 'Only admin can return submitted grades to draft';
    end if;
  elsif old.status = 'APPROVED' and new.status = 'LOCKED' then
    if v_role <> 'ADMIN' then
      raise exception 'Only admin can lock grades';
    end if;
    new.locked_at := timezone('utc', now());
    new.locked_by := v_actor_id;
  elsif old.status = 'APPROVED' and new.status = 'DRAFT' then
    if v_role <> 'ADMIN' then
      raise exception 'Only admin can move approved grades to draft';
    end if;
    new.approved_at := null;
    new.approved_by := null;
    new.locked_at := null;
    new.locked_by := null;
  elsif old.status = 'LOCKED' and new.status = 'APPROVED' then
    if v_role <> 'ADMIN' then
      raise exception 'Only admin can unlock grades';
    end if;
    new.locked_at := null;
    new.locked_by := null;
  else
    raise exception 'Unsupported grade status transition: % -> %', old.status, new.status;
  end if;

  return new;
end;
$$;

create or replace function public.log_grade_change()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if row_to_json(old) is distinct from row_to_json(new) then
    insert into public.grade_change_logs (
      grade_id,
      changed_by,
      change_type,
      old_payload,
      new_payload,
      is_demo,
      demo_batch
    )
    values (
      new.id,
      auth.uid(),
      case
        when new.status is distinct from old.status then 'STATUS_CHANGED'
        else 'SCORE_CHANGED'
      end,
      to_jsonb(old),
      to_jsonb(new),
      new.is_demo,
      new.demo_batch
    );
  end if;

  return new;
end;
$$;

create or replace function public.log_audit_event(
  p_action text,
  p_entity_type text,
  p_entity_id text default null,
  p_target_user_id uuid default null,
  p_metadata jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_log_id bigint;
  v_actor_id uuid := auth.uid();
  v_request_role text := coalesce(auth.role(), '');
  v_actor_role text;
  v_action text := upper(trim(coalesce(p_action, '')));
  v_entity_type text := lower(trim(coalesce(p_entity_type, '')));
  v_raw_metadata jsonb := coalesce(p_metadata, '{}'::jsonb);
  v_metadata jsonb := '{}'::jsonb;
  v_allowed_actions text[];
begin
  if v_actor_id is null and v_request_role = 'service_role' then
    begin
      v_actor_id := nullif(v_raw_metadata ->> '__actor_id', '')::uuid;
    exception
      when others then
        raise exception 'Invalid service actor id in audit metadata';
    end;
  end if;

  if v_actor_id is null then
    raise exception 'Authentication required for audit logging';
  end if;

  if v_request_role <> 'service_role' and (v_raw_metadata ? '__actor_id') then
    raise exception 'Reserved metadata key "__actor_id" is not allowed';
  end if;

  v_metadata := v_raw_metadata - '__actor_id';

  select p.role_code
  into v_actor_role
  from public.profiles p
  where p.id = v_actor_id
    and p.status = 'ACTIVE'
  limit 1;

  if v_actor_role is null then
    raise exception 'Active actor profile is required for audit logging';
  end if;

  if v_action = '' or v_action !~ '^[A-Z0-9_]{3,80}$' then
    raise exception 'Invalid audit action';
  end if;

  if v_entity_type not in (
    'academic_classes',
    'auth',
    'course_offerings',
    'courses',
    'departments',
    'enrollments',
    'grades',
    'lecturers',
    'majors',
    'profiles',
    'regrade_requests',
    'rooms',
    'schedules',
    'semesters',
    'students'
  ) then
    raise exception 'Invalid audit entity_type';
  end if;

  if pg_column_size(v_metadata) > 16384 then
    raise exception 'Audit metadata payload is too large';
  end if;

  if v_actor_role = 'STUDENT' then
    v_allowed_actions := array[
      'AUTH_LOGIN',
      'PASSWORD_RESET',
      'PROFILE_UPDATED',
      'ENROLLMENT_REGISTER_TRIGGERED',
      'ENROLLMENT_CANCEL_TRIGGERED',
      'ENROLLMENT_REGISTERED',
      'ENROLLMENT_DROPPED',
      'REGRADE_REQUEST_CREATED'
    ];
  elsif v_actor_role = 'LECTURER' then
    v_allowed_actions := array[
      'AUTH_LOGIN',
      'PASSWORD_RESET',
      'PROFILE_UPDATED',
      'GRADE_SAVED',
      'GRADE_SHEET_SUBMITTED',
      'REGRADE_REQUEST_RESOLVED'
    ];
  elsif v_actor_role = 'ADMIN' then
    v_allowed_actions := array[
      'ACADEMIC_CLASS_UPDATED',
      'ACADEMIC_CLASS_CREATED',
      'ACADEMIC_CLASS_ACTIVATED',
      'ACADEMIC_CLASS_DEACTIVATED',
      'AUTH_LOGIN',
      'PASSWORD_RESET',
      'COURSE_OFFERING_UPDATED',
      'COURSE_OFFERING_CREATED',
      'COURSE_OFFERING_DELETED',
      'COURSE_UPDATED',
      'COURSE_CREATED',
      'COURSE_DELETED',
      'DEPARTMENT_UPDATED',
      'DEPARTMENT_CREATED',
      'DEPARTMENT_DELETED',
      'ENROLLMENT_REGISTER_TRIGGERED',
      'ENROLLMENT_CANCEL_TRIGGERED',
      'ENROLLMENT_REGISTERED',
      'ENROLLMENT_DROPPED',
      'GRADE_STATUS_CHANGED',
      'GRADE_BATCH_STATUS_CHANGED',
      'GRADE_SAVED',
      'GRADE_SHEET_SUBMITTED',
      'LECTURER_UPDATED',
      'LECTURER_CREATED',
      'LECTURER_ACTIVATED',
      'LECTURER_DEACTIVATED',
      'MAJOR_UPDATED',
      'MAJOR_CREATED',
      'MAJOR_ACTIVATED',
      'MAJOR_DEACTIVATED',
      'PROFILE_UPDATED',
      'REGRADE_REQUEST_CREATED',
      'REGRADE_REQUEST_RESOLVED',
      'ROOM_UPDATED',
      'ROOM_CREATED',
      'ROOM_ACTIVATED',
      'ROOM_DEACTIVATED',
      'SCHEDULE_UPDATED',
      'SCHEDULE_CREATED',
      'SEMESTER_UPDATED',
      'SEMESTER_CREATED',
      'SEMESTER_DELETED',
      'STUDENT_UPDATED',
      'STUDENT_CREATED',
      'STUDENT_ACTIVATED',
      'STUDENT_DEACTIVATED',
      'USER_PROVISIONED',
      'USER_UPDATED'
    ];
  else
    raise exception 'Unsupported role for audit logging';
  end if;

  if not (v_action = any(v_allowed_actions)) then
    raise exception 'Audit action "%" is not allowed for role "%"', v_action, v_actor_role;
  end if;

  insert into public.audit_logs (
    actor_id,
    actor_role,
    action,
    entity_type,
    entity_id,
    target_user_id,
    metadata
  )
  values (
    v_actor_id,
    v_actor_role,
    v_action,
    v_entity_type,
    p_entity_id,
    p_target_user_id,
    v_metadata
  )
  returning id into v_log_id;

  return v_log_id;
end;
$$;

create or replace function public.register_enrollment(p_offering_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_profile public.profiles;
  v_student public.students;
  v_offering record;
  v_existing_enrollment record;
  v_current_credits integer;
  v_missing_prerequisite text;
  v_conflict boolean;
  v_enrollment_id uuid;
begin
  if v_actor_id is null then
    raise exception 'Authentication required';
  end if;

  select * into v_profile
  from public.profiles
  where id = v_actor_id;

  if not found or v_profile.role_code <> 'STUDENT' then
    raise exception 'Only students can register for course offerings';
  end if;

  if v_profile.status <> 'ACTIVE' then
    raise exception 'Your account is not active';
  end if;

  select * into v_student
  from public.students
  where id = v_actor_id;

  if not found or v_student.current_status <> 'ACTIVE' then
    raise exception 'Your student profile is not active';
  end if;

  select
    co.*,
    s.max_credits as semester_max_credits,
    c.credit_hours as course_credit_hours
  into v_offering
  from public.course_offerings co
  join public.semesters s on s.id = co.semester_id
  join public.courses c on c.id = co.course_id
  where co.id = p_offering_id
  for update;

  if not found then
    raise exception 'Course offering not found';
  end if;

  if v_offering.status <> 'OPEN' then
    raise exception 'Course offering is not open for registration';
  end if;

  if timezone('utc', now()) < v_offering.registration_open_at
     or timezone('utc', now()) > v_offering.registration_close_at
  then
    raise exception 'Registration window is closed';
  end if;

  select e.id, e.status
  into v_existing_enrollment
  from public.enrollments e
  where e.student_id = v_actor_id
    and e.course_offering_id = p_offering_id
  for update;

  if v_existing_enrollment.id is not null
     and v_existing_enrollment.status <> 'DROPPED'
  then
    raise exception 'You are already registered for this course offering';
  end if;

  select c.code
  into v_missing_prerequisite
  from public.course_prerequisites cp
  join public.courses c on c.id = cp.prerequisite_course_id
  where cp.course_id = v_offering.course_id
    and not exists (
      select 1
      from public.grades g
      join public.enrollments e on e.id = g.enrollment_id
      join public.course_offerings previous_offering on previous_offering.id = e.course_offering_id
      where e.student_id = v_actor_id
        and previous_offering.course_id = cp.prerequisite_course_id
        and e.status <> 'DROPPED'
        and g.status in ('APPROVED', 'LOCKED')
        and coalesce(g.total_score, 0) >= cp.minimum_score
    )
  limit 1;

  if v_missing_prerequisite is not null then
    raise exception 'Missing prerequisite course: %', v_missing_prerequisite;
  end if;

  select exists (
    select 1
    from public.enrollments e
    join public.course_offerings current_offering on current_offering.id = e.course_offering_id
    join public.schedules existing_schedule on existing_schedule.course_offering_id = current_offering.id
    join public.schedules new_schedule on new_schedule.course_offering_id = p_offering_id
    where e.student_id = v_actor_id
      and e.status = 'ENROLLED'
      and current_offering.semester_id = v_offering.semester_id
      and existing_schedule.day_of_week = new_schedule.day_of_week
      and existing_schedule.time_range && new_schedule.time_range
  ) into v_conflict;

  if v_conflict then
    raise exception 'Schedule conflict detected';
  end if;

  select coalesce(sum(c.credit_hours), 0)
  into v_current_credits
  from public.enrollments e
  join public.course_offerings co on co.id = e.course_offering_id
  join public.courses c on c.id = co.course_id
  where e.student_id = v_actor_id
    and e.status = 'ENROLLED'
    and co.semester_id = v_offering.semester_id;

  if v_current_credits + v_offering.course_credit_hours > v_offering.semester_max_credits then
    raise exception 'Credit limit exceeded for this semester';
  end if;

  if v_offering.enrolled_count >= v_offering.max_capacity then
    raise exception 'Course offering is full';
  end if;

  if v_existing_enrollment.id is not null and v_existing_enrollment.status = 'DROPPED' then
    update public.enrollments
    set
      status = 'ENROLLED',
      enrolled_at = timezone('utc', now()),
      dropped_at = null,
      drop_reason = null,
      is_demo = v_offering.is_demo,
      demo_batch = v_offering.demo_batch
    where id = v_existing_enrollment.id
    returning id into v_enrollment_id;
  else
    insert into public.enrollments (
      student_id,
      course_offering_id,
      status,
      is_demo,
      demo_batch
    )
    values (
      v_actor_id,
      p_offering_id,
      'ENROLLED',
      v_offering.is_demo,
      v_offering.demo_batch
    )
    returning id into v_enrollment_id;
  end if;

  update public.course_offerings
  set enrolled_count = enrolled_count + 1
  where id = p_offering_id;

  perform public.log_audit_event(
    'ENROLLMENT_REGISTERED',
    'enrollments',
    v_enrollment_id::text,
    v_actor_id,
    jsonb_build_object(
      'course_offering_id', p_offering_id,
      'student_id', v_actor_id,
      'reactivated', (v_existing_enrollment.id is not null and v_existing_enrollment.status = 'DROPPED')
    )
  );

  return v_enrollment_id;
end;
$$;

create or replace function public.cancel_enrollment(
  p_enrollment_id uuid,
  p_reason text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_role text := public.current_user_role();
  v_enrollment record;
begin
  if v_actor_id is null then
    raise exception 'Authentication required';
  end if;

  select
    e.*,
    co.registration_open_at,
    co.registration_close_at
  into v_enrollment
  from public.enrollments e
  join public.course_offerings co on co.id = e.course_offering_id
  where e.id = p_enrollment_id
  for update;

  if not found then
    raise exception 'Enrollment not found';
  end if;

  if v_enrollment.status <> 'ENROLLED' then
    raise exception 'Enrollment is already cancelled or completed';
  end if;

  if v_role = 'STUDENT' and v_enrollment.student_id <> v_actor_id then
    raise exception 'You can only cancel your own enrollment';
  end if;

  if v_role = 'STUDENT'
     and (
       timezone('utc', now()) < v_enrollment.registration_open_at
       or timezone('utc', now()) > v_enrollment.registration_close_at
     ) then
    raise exception 'Cancellation window is closed';
  end if;

  if v_role not in ('ADMIN', 'STUDENT') then
    raise exception 'You do not have permission to cancel enrollment';
  end if;

  update public.enrollments
  set
    status = 'DROPPED',
    dropped_at = timezone('utc', now()),
    drop_reason = p_reason
  where id = p_enrollment_id;

  update public.course_offerings
  set enrolled_count = greatest(enrolled_count - 1, 0)
  where id = v_enrollment.course_offering_id;

  perform public.log_audit_event(
    'ENROLLMENT_DROPPED',
    'enrollments',
    p_enrollment_id::text,
    v_enrollment.student_id,
    jsonb_build_object('reason', p_reason)
  );

  return true;
end;
$$;

create or replace function public.calculate_student_cumulative_gpa4(p_student_id uuid)
returns numeric
language sql
stable
set search_path = public
as $$
  select round(
    coalesce(
      sum(g.gpa_value * c.credit_hours) / nullif(sum(c.credit_hours), 0),
      0
    )::numeric,
    2
  )
  from public.grades g
  join public.enrollments e on e.id = g.enrollment_id
  join public.course_offerings co on co.id = e.course_offering_id
  join public.courses c on c.id = co.course_id
  where e.student_id = p_student_id
    and g.status in ('APPROVED', 'LOCKED')
    and e.status <> 'DROPPED';
$$;

create or replace function public.calculate_student_cumulative_score10(p_student_id uuid)
returns numeric
language sql
stable
set search_path = public
as $$
  select round(
    coalesce(
      sum(g.total_score * c.credit_hours) / nullif(sum(c.credit_hours), 0),
      0
    )::numeric,
    2
  )
  from public.grades g
  join public.enrollments e on e.id = g.enrollment_id
  join public.course_offerings co on co.id = e.course_offering_id
  join public.courses c on c.id = co.course_id
  where e.student_id = p_student_id
    and g.status in ('APPROVED', 'LOCKED')
    and e.status <> 'DROPPED';
$$;

drop view if exists public.report_student_distribution;
create view public.report_student_distribution
with (security_invoker = true)
as
select
  d.id as department_id,
  d.code as department_code,
  d.name as department_name,
  m.id as major_id,
  m.code as major_code,
  m.name as major_name,
  ac.id as academic_class_id,
  ac.code as academic_class_code,
  ac.name as academic_class_name,
  count(s.id)::int as total_students
from public.academic_classes ac
join public.majors m on m.id = ac.major_id
join public.departments d on d.id = m.department_id
left join public.students s on s.academic_class_id = ac.id and s.current_status <> 'DROPPED'
group by d.id, d.code, d.name, m.id, m.code, m.name, ac.id, ac.code, ac.name;

drop view if exists public.report_course_pass_rate;
create view public.report_course_pass_rate
with (security_invoker = true)
as
select
  c.id as course_id,
  c.code as course_code,
  c.name as course_name,
  count(g.id)::int as total_completed,
  count(*) filter (where coalesce(g.total_score, 0) >= co.passing_score)::int as total_passed,
  count(*) filter (where coalesce(g.total_score, 0) < co.passing_score)::int as total_failed,
  round(
    coalesce(
      (count(*) filter (where coalesce(g.total_score, 0) >= co.passing_score)::numeric
        / nullif(count(g.id), 0)::numeric) * 100,
      0
    ),
    2
  ) as pass_rate
from public.course_offerings co
join public.courses c on c.id = co.course_id
left join public.enrollments e on e.course_offering_id = co.id and e.status <> 'DROPPED'
left join public.grades g on g.enrollment_id = e.id and g.status in ('APPROVED', 'LOCKED')
group by c.id, c.code, c.name, co.passing_score;

drop view if exists public.report_class_gpa_average;
create view public.report_class_gpa_average
with (security_invoker = true)
as
select
  ac.id as academic_class_id,
  ac.code as class_code,
  ac.name as class_name,
  sem.id as semester_id,
  sem.name as semester_name,
  round(avg(g.gpa_value)::numeric, 2) as average_gpa4,
  round(avg(g.total_score)::numeric, 2) as average_score10
from public.students s
join public.academic_classes ac on ac.id = s.academic_class_id
join public.enrollments e on e.student_id = s.id and e.status <> 'DROPPED'
join public.grades g on g.enrollment_id = e.id and g.status in ('APPROVED', 'LOCKED')
join public.course_offerings co on co.id = e.course_offering_id
join public.semesters sem on sem.id = co.semester_id
group by ac.id, ac.code, ac.name, sem.id, sem.name;

drop view if exists public.report_academic_warnings;
create view public.report_academic_warnings
with (security_invoker = true)
as
select
  s.id as student_id,
  s.student_code,
  p.full_name as student_name,
  ac.code as class_code,
  coalesce(sum(c.credit_hours), 0)::int as completed_credits,
  public.calculate_student_cumulative_gpa4(s.id) as cumulative_gpa4,
  public.calculate_student_cumulative_score10(s.id) as cumulative_score10
from public.students s
join public.profiles p on p.id = s.id
join public.academic_classes ac on ac.id = s.academic_class_id
left join public.enrollments e on e.student_id = s.id and e.status <> 'DROPPED'
left join public.grades g on g.enrollment_id = e.id and g.status in ('APPROVED', 'LOCKED')
left join public.course_offerings co on co.id = e.course_offering_id
left join public.courses c on c.id = co.course_id
group by s.id, s.student_code, p.full_name, ac.code
having public.calculate_student_cumulative_gpa4(s.id) < 2.0;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists departments_set_updated_at on public.departments;
create trigger departments_set_updated_at before update on public.departments for each row execute function public.set_updated_at();
drop trigger if exists majors_set_updated_at on public.majors;
create trigger majors_set_updated_at before update on public.majors for each row execute function public.set_updated_at();
drop trigger if exists academic_classes_set_updated_at on public.academic_classes;
create trigger academic_classes_set_updated_at before update on public.academic_classes for each row execute function public.set_updated_at();
drop trigger if exists semesters_set_updated_at on public.semesters;
create trigger semesters_set_updated_at before update on public.semesters for each row execute function public.set_updated_at();
drop trigger if exists courses_set_updated_at on public.courses;
create trigger courses_set_updated_at before update on public.courses for each row execute function public.set_updated_at();
drop trigger if exists rooms_set_updated_at on public.rooms;
create trigger rooms_set_updated_at before update on public.rooms for each row execute function public.set_updated_at();
drop trigger if exists lecturers_set_updated_at on public.lecturers;
create trigger lecturers_set_updated_at before update on public.lecturers for each row execute function public.set_updated_at();
drop trigger if exists students_set_updated_at on public.students;
create trigger students_set_updated_at before update on public.students for each row execute function public.set_updated_at();
drop trigger if exists course_offerings_set_updated_at on public.course_offerings;
create trigger course_offerings_set_updated_at before update on public.course_offerings for each row execute function public.set_updated_at();
drop trigger if exists schedules_set_updated_at on public.schedules;
create trigger schedules_set_updated_at before update on public.schedules for each row execute function public.set_updated_at();
drop trigger if exists enrollments_set_updated_at on public.enrollments;
create trigger enrollments_set_updated_at before update on public.enrollments for each row execute function public.set_updated_at();
drop trigger if exists grades_set_updated_at on public.grades;
create trigger grades_set_updated_at before update on public.grades for each row execute function public.set_updated_at();
drop trigger if exists regrade_requests_set_updated_at on public.regrade_requests;
create trigger regrade_requests_set_updated_at before update on public.regrade_requests for each row execute function public.set_updated_at();
drop trigger if exists grades_recompute_fields on public.grades;
create trigger grades_recompute_fields before insert or update of attendance_score, midterm_score, final_score on public.grades for each row execute function public.recompute_grade_derived_fields();
drop trigger if exists grades_apply_status_transition on public.grades;
create trigger grades_apply_status_transition before update on public.grades for each row execute function public.apply_grade_status_transition();
drop trigger if exists grades_log_change on public.grades;
create trigger grades_log_change after update on public.grades for each row execute function public.log_grade_change();

alter table public.roles enable row level security;
alter table public.profiles enable row level security;
alter table public.departments enable row level security;
alter table public.majors enable row level security;
alter table public.academic_classes enable row level security;
alter table public.semesters enable row level security;
alter table public.courses enable row level security;
alter table public.course_prerequisites enable row level security;
alter table public.rooms enable row level security;
alter table public.lecturers enable row level security;
alter table public.students enable row level security;
alter table public.course_offerings enable row level security;
alter table public.teaching_assignments enable row level security;
alter table public.schedules enable row level security;
alter table public.enrollments enable row level security;
alter table public.grades enable row level security;
alter table public.grade_change_logs enable row level security;
alter table public.regrade_requests enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists roles_read_authenticated on public.roles;
create policy roles_read_authenticated on public.roles for select to authenticated using (true);

drop policy if exists profiles_select_self_or_admin on public.profiles;
create policy profiles_select_self_or_admin
on public.profiles
for select
to authenticated
using (public.is_admin() or auth.uid() = id);

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin
on public.profiles
for update
to authenticated
using (public.is_admin() or auth.uid() = id)
with check (public.is_admin() or auth.uid() = id);

drop policy if exists admin_insert_profiles on public.profiles;
create policy admin_insert_profiles on public.profiles for insert to authenticated with check (public.is_admin());

drop policy if exists admin_full_departments on public.departments;
create policy admin_full_departments
on public.departments
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists read_departments_authenticated on public.departments;
create policy read_departments_authenticated on public.departments for select to authenticated using (true);

drop policy if exists admin_full_majors on public.majors;
create policy admin_full_majors on public.majors for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read_majors_authenticated on public.majors;
create policy read_majors_authenticated on public.majors for select to authenticated using (true);

drop policy if exists admin_full_academic_classes on public.academic_classes;
create policy admin_full_academic_classes on public.academic_classes for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read_academic_classes_authenticated on public.academic_classes;
create policy read_academic_classes_authenticated on public.academic_classes for select to authenticated using (true);

drop policy if exists admin_full_semesters on public.semesters;
create policy admin_full_semesters on public.semesters for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read_semesters_authenticated on public.semesters;
create policy read_semesters_authenticated on public.semesters for select to authenticated using (true);

drop policy if exists admin_full_courses on public.courses;
create policy admin_full_courses on public.courses for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read_courses_authenticated on public.courses;
create policy read_courses_authenticated on public.courses for select to authenticated using (true);

drop policy if exists admin_full_course_prerequisites on public.course_prerequisites;
create policy admin_full_course_prerequisites on public.course_prerequisites for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read_course_prerequisites_authenticated on public.course_prerequisites;
create policy read_course_prerequisites_authenticated on public.course_prerequisites for select to authenticated using (true);

drop policy if exists admin_full_rooms on public.rooms;
create policy admin_full_rooms on public.rooms for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists read_rooms_authenticated on public.rooms;
create policy read_rooms_authenticated on public.rooms for select to authenticated using (true);

drop policy if exists lecturers_select_policy on public.lecturers;
create policy lecturers_select_policy
on public.lecturers
for select
to authenticated
using (public.is_admin() or auth.uid() = id or public.current_user_role() in ('LECTURER', 'STUDENT'));

drop policy if exists admin_manage_lecturers on public.lecturers;
create policy admin_manage_lecturers on public.lecturers for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists students_select_policy on public.students;
create policy students_select_policy
on public.students
for select
to authenticated
using (
  public.is_admin()
  or auth.uid() = id
  or exists (
    select 1
    from public.enrollments e
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where e.student_id = students.id
      and ta.lecturer_id = auth.uid()
  )
);

drop policy if exists admin_manage_students on public.students;
create policy admin_manage_students on public.students for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists read_course_offerings_authenticated on public.course_offerings;
create policy read_course_offerings_authenticated on public.course_offerings for select to authenticated using (true);
drop policy if exists admin_manage_course_offerings on public.course_offerings;
create policy admin_manage_course_offerings on public.course_offerings for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists read_teaching_assignments_authenticated on public.teaching_assignments;
create policy read_teaching_assignments_authenticated on public.teaching_assignments for select to authenticated using (true);
drop policy if exists admin_manage_teaching_assignments on public.teaching_assignments;
create policy admin_manage_teaching_assignments on public.teaching_assignments for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists read_schedules_authenticated on public.schedules;
create policy read_schedules_authenticated on public.schedules for select to authenticated using (true);
drop policy if exists admin_manage_schedules on public.schedules;
create policy admin_manage_schedules on public.schedules for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists enrollments_select_policy on public.enrollments;
create policy enrollments_select_policy
on public.enrollments
for select
to authenticated
using (
  public.is_admin()
  or student_id = auth.uid()
  or exists (
    select 1
    from public.teaching_assignments ta
    where ta.course_offering_id = enrollments.course_offering_id
      and ta.lecturer_id = auth.uid()
  )
);

drop policy if exists admin_manage_enrollments on public.enrollments;
create policy admin_manage_enrollments on public.enrollments for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists grades_select_policy on public.grades;
create policy grades_select_policy
on public.grades
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.enrollments e
    where e.id = grades.enrollment_id
      and e.student_id = auth.uid()
  )
  or exists (
    select 1
    from public.enrollments e
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where e.id = grades.enrollment_id
      and ta.lecturer_id = auth.uid()
  )
);

drop policy if exists grades_insert_policy on public.grades;
create policy grades_insert_policy
on public.grades
for insert
to authenticated
with check (
  public.is_admin()
  or exists (
    select 1
    from public.enrollments e
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where e.id = grades.enrollment_id
      and ta.lecturer_id = auth.uid()
  )
);

drop policy if exists grades_update_policy on public.grades;
create policy grades_update_policy
on public.grades
for update
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.enrollments e
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where e.id = grades.enrollment_id
      and ta.lecturer_id = auth.uid()
  )
)
with check (
  public.is_admin()
  or (
    status in ('DRAFT', 'SUBMITTED')
    and exists (
      select 1
      from public.enrollments e
      join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
      where e.id = grades.enrollment_id
        and ta.lecturer_id = auth.uid()
    )
  )
);

drop policy if exists grade_change_logs_select_policy on public.grade_change_logs;
create policy grade_change_logs_select_policy
on public.grade_change_logs
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.grades g
    join public.enrollments e on e.id = g.enrollment_id
    where g.id = grade_change_logs.grade_id
      and e.student_id = auth.uid()
  )
  or exists (
    select 1
    from public.grades g
    join public.enrollments e on e.id = g.enrollment_id
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where g.id = grade_change_logs.grade_id
      and ta.lecturer_id = auth.uid()
  )
);

drop policy if exists regrade_requests_select_policy on public.regrade_requests;
create policy regrade_requests_select_policy
on public.regrade_requests
for select
to authenticated
using (
  public.is_admin()
  or student_id = auth.uid()
  or exists (
    select 1
    from public.enrollments e
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where e.id = regrade_requests.enrollment_id
      and ta.lecturer_id = auth.uid()
  )
);

drop policy if exists regrade_requests_insert_student on public.regrade_requests;
create policy regrade_requests_insert_student
on public.regrade_requests
for insert
to authenticated
with check (
  student_id = auth.uid()
  and exists (
    select 1
    from public.grades g
    join public.enrollments e on e.id = g.enrollment_id
    join public.course_offerings co on co.id = e.course_offering_id
    join public.semesters s on s.id = co.semester_id
    where g.id = regrade_requests.grade_id
      and e.id = regrade_requests.enrollment_id
      and e.student_id = auth.uid()
      and g.status in ('APPROVED', 'LOCKED')
      and (
        s.regrade_open_at is null
        or s.regrade_close_at is null
        or timezone('utc', now()) between s.regrade_open_at and s.regrade_close_at
      )
  )
);

drop policy if exists regrade_requests_update_policy on public.regrade_requests;
create policy regrade_requests_update_policy
on public.regrade_requests
for update
to authenticated
using (
  public.is_admin()
  or exists (
    select 1
    from public.enrollments e
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where e.id = regrade_requests.enrollment_id
      and ta.lecturer_id = auth.uid()
  )
)
with check (
  public.is_admin()
  or exists (
    select 1
    from public.enrollments e
    join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
    where e.id = regrade_requests.enrollment_id
      and ta.lecturer_id = auth.uid()
  )
);

drop policy if exists audit_logs_admin_only on public.audit_logs;
create policy audit_logs_admin_only on public.audit_logs for select to authenticated using (public.is_admin());

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_lecturer_assigned(uuid) to authenticated;

create table if not exists public.roles (
  code text primary key,
  name text not null,
  description text
);

insert into public.roles (code, name, description)
values
  ('ADMIN', 'Administrator', 'Full access to manage the system'),
  ('LECTURER', 'Lecturer', 'Can manage grades and teaching workload'),
  ('STUDENT', 'Student', 'Can manage personal study activities')
on conflict (code) do nothing;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email citext not null unique,
  full_name text not null,
  role_code text not null references public.roles (code),
  status profile_status not null default 'ACTIVE',
  phone text,
  avatar_url text,
  must_change_password boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.departments (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.majors (
  id uuid primary key default gen_random_uuid(),
  department_id uuid not null references public.departments (id) on delete restrict,
  code text not null unique,
  name text not null,
  degree_level text not null default 'UNDERGRADUATE',
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.academic_classes (
  id uuid primary key default gen_random_uuid(),
  major_id uuid not null references public.majors (id) on delete restrict,
  code text not null unique,
  name text not null,
  cohort_year integer not null check (cohort_year >= 2000),
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.semesters (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  academic_year text not null,
  start_date date not null,
  end_date date not null,
  enrollment_start timestamptz not null,
  enrollment_end timestamptz not null,
  regrade_open_at timestamptz,
  regrade_close_at timestamptz,
  max_credits integer not null default 21 check (max_credits > 0),
  is_current boolean not null default false,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint semesters_date_check check (start_date <= end_date),
  constraint semesters_enrollment_window_check check (enrollment_start < enrollment_end),
  constraint semesters_regrade_window_check check (
    regrade_open_at is null
    or regrade_close_at is null
    or regrade_open_at < regrade_close_at
  )
);

create table if not exists public.courses (
  id uuid primary key default gen_random_uuid(),
  department_id uuid not null references public.departments (id) on delete restrict,
  code text not null unique,
  name text not null,
  credit_hours integer not null check (credit_hours > 0),
  total_sessions smallint not null default 15 check (total_sessions > 0),
  description text,
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.course_prerequisites (
  course_id uuid not null references public.courses (id) on delete cascade,
  prerequisite_course_id uuid not null references public.courses (id) on delete restrict,
  minimum_score numeric(4, 2) not null default 5.00 check (minimum_score >= 0 and minimum_score <= 10),
  created_at timestamptz not null default timezone('utc', now()),
  primary key (course_id, prerequisite_course_id),
  constraint course_prerequisites_self_check check (course_id <> prerequisite_course_id)
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  building text,
  capacity integer not null check (capacity > 0),
  is_active boolean not null default true,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.lecturers (
  id uuid primary key references public.profiles (id) on delete cascade,
  employee_code text not null unique,
  department_id uuid not null references public.departments (id) on delete restrict,
  academic_title text,
  hire_date date,
  office_location text,
  bio text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.students (
  id uuid primary key references public.profiles (id) on delete cascade,
  student_code text not null unique,
  academic_class_id uuid not null references public.academic_classes (id) on delete restrict,
  enrollment_year integer not null check (enrollment_year >= 2000),
  current_status student_status not null default 'ACTIVE',
  gender text,
  date_of_birth date,
  address text,
  emergency_contact text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.course_offerings (
  id uuid primary key default gen_random_uuid(),
  course_id uuid not null references public.courses (id) on delete restrict,
  semester_id uuid not null references public.semesters (id) on delete restrict,
  section_code text not null,
  title text,
  max_capacity integer not null check (max_capacity > 0),
  enrolled_count integer not null default 0 check (enrolled_count >= 0),
  registration_open_at timestamptz not null,
  registration_close_at timestamptz not null,
  attendance_weight numeric(5, 2) not null default 10.00 check (attendance_weight >= 0 and attendance_weight <= 100),
  midterm_weight numeric(5, 2) not null default 30.00 check (midterm_weight >= 0 and midterm_weight <= 100),
  final_weight numeric(5, 2) not null default 60.00 check (final_weight >= 0 and final_weight <= 100),
  passing_score numeric(4, 2) not null default 5.00 check (passing_score >= 0 and passing_score <= 10),
  status offering_status not null default 'DRAFT',
  notes text,
  created_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint course_offerings_registration_window_check check (registration_open_at < registration_close_at),
  constraint course_offerings_weight_sum_check check (
    attendance_weight + midterm_weight + final_weight = 100.00
  ),
  constraint course_offerings_unique_section unique (semester_id, course_id, section_code)
);

create table if not exists public.teaching_assignments (
  id uuid primary key default gen_random_uuid(),
  course_offering_id uuid not null references public.course_offerings (id) on delete cascade,
  lecturer_id uuid not null references public.lecturers (id) on delete cascade,
  assignment_role text not null default 'PRIMARY',
  is_primary boolean not null default false,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  unique (course_offering_id, lecturer_id)
);

create table if not exists public.schedules (
  id uuid primary key default gen_random_uuid(),
  course_offering_id uuid not null references public.course_offerings (id) on delete cascade,
  room_id uuid references public.rooms (id) on delete set null,
  day_of_week smallint not null check (day_of_week between 1 and 7),
  start_time time not null,
  end_time time not null,
  week_pattern text not null default 'ALL',
  start_date date,
  end_date date,
  note text,
  time_range int4range generated always as (
    int4range(
      (extract(hour from start_time)::int * 60) + extract(minute from start_time)::int,
      (extract(hour from end_time)::int * 60) + extract(minute from end_time)::int,
      '[)'
    )
  ) stored,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint schedules_time_check check (start_time < end_time),
  constraint schedules_date_check check (start_date is null or end_date is null or start_date <= end_date)
);

create table if not exists public.enrollments (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.students (id) on delete cascade,
  course_offering_id uuid not null references public.course_offerings (id) on delete cascade,
  status enrollment_status not null default 'ENROLLED',
  enrolled_at timestamptz not null default timezone('utc', now()),
  dropped_at timestamptz,
  drop_reason text,
  approved_by uuid references public.profiles (id),
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint enrollments_unique_student_offering unique (student_id, course_offering_id)
);

create table if not exists public.grades (
  id uuid primary key default gen_random_uuid(),
  enrollment_id uuid not null unique references public.enrollments (id) on delete cascade,
  attendance_score numeric(4, 2) check (attendance_score >= 0 and attendance_score <= 10),
  midterm_score numeric(4, 2) check (midterm_score >= 0 and midterm_score <= 10),
  final_score numeric(4, 2) check (final_score >= 0 and final_score <= 10),
  total_score numeric(4, 2),
  letter_grade text,
  gpa_value numeric(3, 2),
  status grade_status not null default 'DRAFT',
  submitted_at timestamptz,
  submitted_by uuid references public.profiles (id),
  approved_at timestamptz,
  approved_by uuid references public.profiles (id),
  locked_at timestamptz,
  locked_by uuid references public.profiles (id),
  remark text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.grade_change_logs (
  id uuid primary key default gen_random_uuid(),
  grade_id uuid not null references public.grades (id) on delete cascade,
  changed_by uuid references public.profiles (id),
  change_type text not null,
  old_payload jsonb not null default '{}'::jsonb,
  new_payload jsonb not null default '{}'::jsonb,
  note text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.regrade_requests (
  id uuid primary key default gen_random_uuid(),
  grade_id uuid not null references public.grades (id) on delete cascade,
  enrollment_id uuid not null references public.enrollments (id) on delete cascade,
  student_id uuid not null references public.students (id) on delete cascade,
  reason text not null,
  status regrade_status not null default 'PENDING',
  previous_total_score numeric(4, 2),
  resolved_total_score numeric(4, 2),
  reviewed_at timestamptz,
  reviewed_by uuid references public.profiles (id),
  resolution_note text,
  is_demo boolean not null default false,
  demo_batch text,
  submitted_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references public.profiles (id),
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  target_user_id uuid references public.profiles (id),
  metadata jsonb not null default '{}'::jsonb,
  ip_address inet,
  user_agent text,
  is_demo boolean not null default false,
  demo_batch text,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists teaching_assignments_one_primary_idx
  on public.teaching_assignments (course_offering_id)
  where is_primary;

create unique index if not exists regrade_requests_one_open_request_idx
  on public.regrade_requests (grade_id, student_id)
  where status in ('PENDING', 'UNDER_REVIEW');

create index if not exists profiles_role_idx on public.profiles (role_code, status);
create index if not exists departments_active_idx on public.departments (is_active);
create index if not exists majors_department_idx on public.majors (department_id);
create index if not exists academic_classes_major_idx on public.academic_classes (major_id, cohort_year);
create index if not exists lecturers_department_idx on public.lecturers (department_id);
create index if not exists students_class_idx on public.students (academic_class_id, current_status);
create index if not exists course_offerings_semester_idx on public.course_offerings (semester_id, status);
create index if not exists teaching_assignments_lecturer_idx on public.teaching_assignments (lecturer_id, course_offering_id);
create index if not exists schedules_offering_idx on public.schedules (course_offering_id, day_of_week);
create index if not exists enrollments_student_idx on public.enrollments (student_id, status);
create index if not exists enrollments_offering_idx on public.enrollments (course_offering_id, status);
create index if not exists grades_status_idx on public.grades (status);
create index if not exists regrade_requests_status_idx on public.regrade_requests (status, student_id);
create index if not exists audit_logs_action_idx on public.audit_logs (action, created_at desc);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'schedules_room_overlap_excl'
  ) then
    alter table public.schedules
      add constraint schedules_room_overlap_excl
      exclude using gist (
        room_id with =,
        day_of_week with =,
        time_range with &&
      )
      where (room_id is not null);
  end if;
end $$;


-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/0002_authz_hardening.sql
-- =====================================================================

create or replace function public.can_student_view_offering(p_offering_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.course_offerings co
    where co.id = p_offering_id
      and (
        co.status = 'OPEN'
        or exists (
          select 1
          from public.enrollments e
          where e.course_offering_id = co.id
            and e.student_id = auth.uid()
        )
      )
  );
$$;

create or replace function public.can_read_course_offering(p_offering_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.is_admin()
    or (
      public.current_user_role() = 'LECTURER'
      and exists (
        select 1
        from public.teaching_assignments ta
        where ta.course_offering_id = p_offering_id
          and ta.lecturer_id = auth.uid()
      )
    )
    or (
      public.current_user_role() = 'STUDENT'
      and public.can_student_view_offering(p_offering_id)
    ),
    false
  );
$$;

grant execute on function public.can_student_view_offering(uuid) to authenticated;
grant execute on function public.can_read_course_offering(uuid) to authenticated;

drop policy if exists profiles_select_self_or_admin on public.profiles;
drop policy if exists profiles_select_scoped on public.profiles;
create policy profiles_select_scoped
on public.profiles
for select
to authenticated
using (
  public.is_admin()
  or auth.uid() = id
  or (
    public.current_user_role() = 'LECTURER'
    and exists (
      select 1
      from public.enrollments e
      join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
      where e.student_id = profiles.id
        and ta.lecturer_id = auth.uid()
    )
  )
  or (
    public.current_user_role() = 'STUDENT'
    and exists (
      select 1
      from public.teaching_assignments ta
      where ta.lecturer_id = profiles.id
        and public.can_read_course_offering(ta.course_offering_id)
    )
  )
);

drop policy if exists lecturers_select_policy on public.lecturers;
create policy lecturers_select_policy
on public.lecturers
for select
to authenticated
using (
  public.is_admin()
  or auth.uid() = id
  or exists (
    select 1
    from public.teaching_assignments ta
    where ta.lecturer_id = lecturers.id
      and public.can_read_course_offering(ta.course_offering_id)
  )
);

drop policy if exists read_course_offerings_authenticated on public.course_offerings;
create policy read_course_offerings_authenticated
on public.course_offerings
for select
to authenticated
using (public.can_read_course_offering(id));

drop policy if exists read_teaching_assignments_authenticated on public.teaching_assignments;
create policy read_teaching_assignments_authenticated
on public.teaching_assignments
for select
to authenticated
using (public.can_read_course_offering(course_offering_id));

drop policy if exists read_schedules_authenticated on public.schedules;
create policy read_schedules_authenticated
on public.schedules
for select
to authenticated
using (public.can_read_course_offering(course_offering_id));


-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/0003_fix_schedule_room_overlap.sql
-- =====================================================================

alter table public.schedules
  add column if not exists active_date_range daterange
  generated always as (
    daterange(
      coalesce(start_date, '-infinity'::date),
      case
        when end_date is null then 'infinity'::date
        else end_date + 1
      end,
      '[)'
    )
  ) stored;

alter table public.schedules
  drop constraint if exists schedules_room_overlap_excl;

alter table public.schedules
  add constraint schedules_room_overlap_excl
  exclude using gist (
    room_id with =,
    day_of_week with =,
    time_range with &&,
    active_date_range with &&
  )
  where (room_id is not null);


-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/20260416154453_sync_with_report.sql
-- =====================================================================

-- Migration: sync schema with report (step 2B)
-- NGUYEN TAC: only additive/backward-compatible changes.
-- KHONG DROP table/cot dang co du lieu.

-- Ghi chu: Van de "0001_init_sms.sql bi lap block CREATE TABLE" la van de lich su file migration.
-- Khong the sua bang mot migration additive moi, nen chi danh dau de team cleanup tai file lich su neu can.

-- =====================================================================
-- 2) THEM COT THIEU / COT TUONG THICH VOI BAO CAO
-- =====================================================================

-- Them cot id cho course_prerequisites: dong bo voi Bang 4.1 trong bao cao final
-- (giu nguyen PK ghep hien tai de backward-compatible, bo sung surrogate key duy nhat).
alter table public.course_prerequisites
  add column if not exists id uuid;

update public.course_prerequisites
set id = gen_random_uuid()
where id is null;

alter table public.course_prerequisites
  alter column id set default gen_random_uuid();

alter table public.course_prerequisites
  alter column id set not null;

create unique index if not exists course_prerequisites_id_key
  on public.course_prerequisites (id);

-- Them cot report_status cho enrollments: dong bo vocabulary status voi bao cao final
-- (REGISTERED/CANCELLED), trong khi van giu cot status goc de khong pha vo nghiep vu hien tai.
alter table public.enrollments
  add column if not exists report_status text;

update public.enrollments
set report_status = case
  when status = 'ENROLLED'::enrollment_status then 'REGISTERED'
  when status = 'DROPPED'::enrollment_status then 'CANCELLED'
  else status::text
end
where report_status is distinct from case
  when status = 'ENROLLED'::enrollment_status then 'REGISTERED'
  when status = 'DROPPED'::enrollment_status then 'CANCELLED'
  else status::text
end;

create or replace function public.sync_enrollments_report_status()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.report_status := case
    when new.status = 'ENROLLED'::enrollment_status then 'REGISTERED'
    when new.status = 'DROPPED'::enrollment_status then 'CANCELLED'
    else new.status::text
  end;
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'enrollments_sync_report_status'
      and tgrelid = 'public.enrollments'::regclass
      and not tgisinternal
  ) then
    create trigger enrollments_sync_report_status
    before insert or update of status
    on public.enrollments
    for each row
    execute function public.sync_enrollments_report_status();
  end if;
end $$;

-- Them cot report_status cho regrade_requests: dong bo status REVIEWING trong bao cao final.
alter table public.regrade_requests
  add column if not exists report_status text;

update public.regrade_requests
set report_status = case
  when status = 'UNDER_REVIEW'::regrade_status then 'REVIEWING'
  else status::text
end
where report_status is distinct from case
  when status = 'UNDER_REVIEW'::regrade_status then 'REVIEWING'
  else status::text
end;

create or replace function public.sync_regrade_requests_report_status()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.report_status := case
    when new.status = 'UNDER_REVIEW'::regrade_status then 'REVIEWING'
    else new.status::text
  end;
  return new;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'regrade_requests_sync_report_status'
      and tgrelid = 'public.regrade_requests'::regclass
      and not tgisinternal
  ) then
    create trigger regrade_requests_sync_report_status
    before insert or update of status
    on public.regrade_requests
    for each row
    execute function public.sync_regrade_requests_report_status();
  end if;
end $$;

-- =====================================================================
-- 3) THEM HAM THIEU (OVERLOAD) THEO BAO CAO
-- =====================================================================

-- Them ham register_enrollment(p_student_id uuid, p_offering_id uuid):
-- dong bo signature voi bao cao final, delegate ve ham hien tai de giu logic nghiep vu.


-- Them ham cancel_enrollment(p_student_id uuid, p_offering_id uuid, p_reason text):
-- dong bo signature voi bao cao final, delegate ve ham hien tai theo enrollment_id.


-- =====================================================================
-- 4) THEM TRIGGER THIEU (TEN DONG BO BAO CAO)
-- =====================================================================

-- Them trigger alias "recompute_grade_derived_fields": dong bo ten trigger voi bao cao final.
-- Dung WHEN (false) de khong thay doi hanh vi vi trigger goc da ton tai (grades_recompute_fields).
do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'recompute_grade_derived_fields'
      and tgrelid = 'public.grades'::regclass
      and not tgisinternal
  ) then
    create trigger recompute_grade_derived_fields
    before insert or update
    on public.grades
    for each row
    when (false)
    execute function public.recompute_grade_derived_fields();
  end if;
end $$;

-- Them trigger alias "apply_grade_status_transition": dong bo ten trigger voi bao cao final.
do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'apply_grade_status_transition'
      and tgrelid = 'public.grades'::regclass
      and not tgisinternal
  ) then
    create trigger apply_grade_status_transition
    before update
    on public.grades
    for each row
    when (false)
    execute function public.apply_grade_status_transition();
  end if;
end $$;

-- Them trigger alias "log_grade_change": dong bo ten trigger voi bao cao final.
do $$
begin
  if not exists (
    select 1
    from pg_trigger
    where tgname = 'log_grade_change'
      and tgrelid = 'public.grades'::regclass
      and not tgisinternal
  ) then
    create trigger log_grade_change
    after update
    on public.grades
    for each row
    when (false)
    execute function public.log_grade_change();
  end if;
end $$;

-- =====================================================================
-- 5) RLS POLICY THIEU
-- =====================================================================
-- Khong co policy thieu theo ket qua 2A; khong them policy moi trong migration nay.


-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/20260416200101_fix_grade_status_transition_p0.sql
-- =====================================================================

-- P0: Enforce strict grade status state machine to protect data integrity.
-- Allowed transitions:
--   DRAFT -> SUBMITTED           (LECTURER, ADMIN)
--   SUBMITTED -> APPROVED        (ADMIN)
--   SUBMITTED -> DRAFT           (ADMIN)
--   APPROVED -> LOCKED           (ADMIN)
--   APPROVED -> DRAFT            (ADMIN)
--   LOCKED -> APPROVED           (ADMIN)
-- Any other transition must be rejected.



-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/20260416200102_harden_audit_log_rpc_p1.sql
-- =====================================================================

-- P1: Harden audit logging RPC to prevent arbitrary writes from authenticated users.
-- Strategy:
-- - Validate actor and role from current session.
-- - Restrict accepted action names by role-specific whitelist.
-- - Restrict entity_type whitelist.
-- - Cap metadata payload size.




-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/20260416200103_add_audit_log_indexes_p1.sql
-- =====================================================================

-- P1: Add missing audit log indexes for actor/time filtering workloads.

create index if not exists audit_logs_actor_idx
  on public.audit_logs (actor_id);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs (created_at desc);


-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/20260416200104_fix_enrollments_student_fk_restrict_p1.sql
-- =====================================================================

-- P1: Preserve enrollment/grade history by preventing student hard-delete cascades.
-- Change FK behavior from ON DELETE CASCADE to ON DELETE RESTRICT.

alter table public.enrollments
  drop constraint if exists enrollments_student_id_fkey;

alter table public.enrollments
  add constraint enrollments_student_id_fkey
  foreign key (student_id)
  references public.students (id)
  on delete restrict;


-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/20260416211001_add_indexes.sql
-- =====================================================================

-- P2 performance: add missing indexes used by regrade queries.
-- Keep names deterministic for easier monitoring.

create index if not exists idx_regrade_requests_student_id
  on public.regrade_requests (student_id);

create index if not exists idx_regrade_requests_grade_id
  on public.regrade_requests (grade_id);


-- =====================================================================
-- SQUASHED FROM: supabase/migrations_archive/20260416211002_tighten_profiles_policy_for_students_p2.sql
-- =====================================================================

-- P2 security hardening: scope student visibility of lecturer profiles
-- to lecturers attached to offerings the student has actually enrolled in.

drop policy if exists profiles_select_scoped on public.profiles;

create policy profiles_select_scoped
on public.profiles
for select
to authenticated
using (
  public.is_admin()
  or auth.uid() = id
  or (
    public.current_user_role() = 'LECTURER'
    and exists (
      select 1
      from public.enrollments e
      join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
      where e.student_id = profiles.id
        and ta.lecturer_id = auth.uid()
    )
  )
  or (
    public.current_user_role() = 'STUDENT'
    and exists (
      select 1
      from public.enrollments e
      join public.teaching_assignments ta on ta.course_offering_id = e.course_offering_id
      where e.student_id = auth.uid()
        and e.status = 'ENROLLED'
        and ta.lecturer_id = profiles.id
    )
  )
);


-- =====================================================================
-- FINAL CANONICAL OVERRIDES
-- =====================================================================

-- Remove compatibility columns / triggers / overload RPCs that were added for legacy report mapping.
drop trigger if exists enrollments_sync_report_status on public.enrollments;
drop function if exists public.sync_enrollments_report_status();
alter table public.enrollments
  drop column if exists report_status;

drop trigger if exists regrade_requests_sync_report_status on public.regrade_requests;
drop function if exists public.sync_regrade_requests_report_status();
alter table public.regrade_requests
  drop column if exists report_status;

drop function if exists public.register_enrollment(uuid, uuid);
drop function if exists public.cancel_enrollment(uuid, uuid, text);

drop trigger if exists recompute_grade_derived_fields on public.grades;
drop trigger if exists apply_grade_status_transition on public.grades;
drop trigger if exists log_grade_change on public.grades;

-- Active-role guard used by RLS helpers and RPC checks.

create or replace function public.is_current_user_active()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.status = 'ACTIVE'
  );
$$;

grant execute on function public.current_user_role() to authenticated;
grant execute on function public.is_current_user_active() to authenticated;

-- Prevent self-service privilege escalation when updating profiles directly.
create or replace function public.protect_profile_self_update()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_role text := current_setting('request.jwt.claim.role', true);
begin
  if v_actor_id is null then
    if v_actor_role = 'service_role' or current_user in ('postgres', 'supabase_admin') then
      return new;
    end if;
    raise exception 'Authentication required';
  end if;

  if public.is_admin() then
    return new;
  end if;

  if new.id <> v_actor_id then
    raise exception 'You can only update your own profile';
  end if;

  if old.role_code is distinct from new.role_code
     or old.status is distinct from new.status
     or old.email is distinct from new.email
     or old.must_change_password is distinct from new.must_change_password
     or old.metadata is distinct from new.metadata
     or old.is_demo is distinct from new.is_demo
     or old.demo_batch is distinct from new.demo_batch
  then
    raise exception 'You are not allowed to update protected profile fields';
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_protect_self_update on public.profiles;
create trigger profiles_protect_self_update
before update on public.profiles
for each row
execute function public.protect_profile_self_update();

drop policy if exists profiles_update_self_or_admin on public.profiles;
create policy profiles_update_self_or_admin
on public.profiles
for update
to authenticated
using (
  public.is_current_user_active()
  and (
    public.is_admin()
    or auth.uid() = id
  )
)
with check (
  public.is_current_user_active()
  and (
    public.is_admin()
    or auth.uid() = id
  )
);

-- Enrollment registration with dropped-row reactivation.


-- Align cancellation action to canonical enrollment lifecycle terminology.


-- Grade status state machine + score mutation guard.

-- Regrade status lifecycle and required payload validations.
create or replace function public.apply_regrade_status_transition()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_role text := public.current_user_role();
  v_actor_id uuid := auth.uid();
begin
  if tg_op <> 'UPDATE' then
    return new;
  end if;

  if v_actor_id is null then
    raise exception 'Authentication required';
  end if;

  if v_role not in ('ADMIN', 'LECTURER') then
    raise exception 'Only admin or lecturer can transition regrade status';
  end if;

  if new.status is not distinct from old.status then
    return new;
  end if;

  if old.status = 'PENDING' and new.status in ('UNDER_REVIEW', 'RESOLVED', 'REJECTED', 'CANCELLED') then
    null;
  elsif old.status = 'UNDER_REVIEW' and new.status in ('RESOLVED', 'REJECTED', 'CANCELLED') then
    null;
  else
    raise exception 'Unsupported regrade status transition: % -> %', old.status, new.status;
  end if;

  if new.status = 'RESOLVED' then
    if new.resolved_total_score is null then
      raise exception 'resolved_total_score is required when status is RESOLVED';
    end if;

    if new.resolved_total_score < 0 or new.resolved_total_score > 10 then
      raise exception 'resolved_total_score must be between 0 and 10';
    end if;

    if nullif(trim(coalesce(new.resolution_note, '')), '') is null then
      raise exception 'resolution_note is required when status is RESOLVED';
    end if;
  end if;

  new.reviewed_at := timezone('utc', now());
  new.reviewed_by := v_actor_id;

  return new;
end;
$$;

drop trigger if exists regrade_requests_apply_status_transition on public.regrade_requests;
create trigger regrade_requests_apply_status_transition
before update on public.regrade_requests
for each row
execute function public.apply_regrade_status_transition();

-- Harden audit logging RPC to trusted server path.

grant execute on function public.register_enrollment(uuid) to authenticated;
grant execute on function public.cancel_enrollment(uuid, text) to authenticated;
revoke execute on function public.log_audit_event(text, text, text, uuid, jsonb) from public;
revoke execute on function public.log_audit_event(text, text, text, uuid, jsonb) from authenticated;
revoke execute on function public.log_audit_event(text, text, text, uuid, jsonb) from anon;
grant execute on function public.log_audit_event(text, text, text, uuid, jsonb) to service_role;

-- One-command SQL helper to activate and promote an existing auth account to ADMIN.
create or replace function public.promote_profile_to_admin(
  p_email text,
  p_full_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_email text := lower(trim(coalesce(p_email, '')));
  v_full_name text := nullif(trim(coalesce(p_full_name, '')), '');
  v_user_id uuid;
begin
  if v_email = '' then
    raise exception 'Email is required';
  end if;

  select u.id
  into v_user_id
  from auth.users u
  where lower(u.email) = v_email
  limit 1;

  if v_user_id is null then
    raise exception 'No auth user found for email %', v_email;
  end if;

  if v_full_name is null then
    select nullif(trim(coalesce(u.raw_user_meta_data ->> 'full_name', '')), '')
    into v_full_name
    from auth.users u
    where u.id = v_user_id;
  end if;

  v_full_name := coalesce(v_full_name, 'System Admin');

  update auth.users
  set
    raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb)
      || jsonb_build_object('role', 'ADMIN'),
    updated_at = timezone('utc', now())
  where id = v_user_id;

  insert into public.profiles (
    id,
    email,
    full_name,
    role_code,
    status,
    must_change_password,
    metadata
  )
  values (
    v_user_id,
    v_email,
    v_full_name,
    'ADMIN',
    'ACTIVE',
    false,
    jsonb_build_object('source', 'promote_profile_to_admin')
  )
  on conflict (id)
  do update set
    email = excluded.email,
    full_name = excluded.full_name,
    role_code = excluded.role_code,
    status = excluded.status,
    must_change_password = false,
    metadata = coalesce(public.profiles.metadata, '{}'::jsonb) || excluded.metadata,
    updated_at = timezone('utc', now());

  return v_user_id;
end;
$$;

revoke execute on function public.promote_profile_to_admin(text, text) from public;
revoke execute on function public.promote_profile_to_admin(text, text) from authenticated;
revoke execute on function public.promote_profile_to_admin(text, text) from anon;
grant execute on function public.promote_profile_to_admin(text, text) to service_role;

-- Query-plan helpers for admin dashboard filters and ilike search.
create index if not exists profiles_status_idx
  on public.profiles (status);

create index if not exists students_status_idx
  on public.students (current_status);

create index if not exists courses_department_active_idx
  on public.courses (department_id, is_active);

create index if not exists courses_is_active_idx
  on public.courses (is_active);

create index if not exists course_offerings_status_idx
  on public.course_offerings (status);

create index if not exists courses_code_trgm_idx
  on public.courses using gin (code gin_trgm_ops);

create index if not exists courses_name_trgm_idx
  on public.courses using gin (name gin_trgm_ops);

create index if not exists students_code_trgm_idx
  on public.students using gin (student_code gin_trgm_ops);

create index if not exists profiles_full_name_trgm_idx
  on public.profiles using gin (full_name gin_trgm_ops);
